name: Detect Python changes
description: Outputs whether *.py files changed and their list
outputs:
  any:
    description: "true/false if any matched files changed"
    value: ${{ steps.detect.outputs.any }}
  list:
    description: "newline-separated list of changed *.py files"
    value: ${{ steps.detect.outputs.list }}
runs:
  using: "composite"
  steps:
    - name: Checkout (full history)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - id: detect
      shell: bash
      run: |
        set -euo pipefail

        HEAD_SHA="${{ github.sha }}"
        DEFAULT_BRANCH="${{ github.event.repository.default_branch || 'main' }}"

        git fetch --no-tags --prune origin "$DEFAULT_BRANCH" --depth=1

        UNIQUE_COMMITS="$(git rev-list --right-only --cherry-pick --no-merges --ancestry-path "origin/$DEFAULT_BRANCH...$HEAD_SHA" || true)"
        
        echo "-------DEBUG (detector)--------"
        echo "HEAD_SHA: $HEAD_SHA"
        echo "Unique commits count: $(printf '%s\n' "$UNIQUE_COMMITS" | sed '/^$/d' | wc -1 || true)"
        echo "-------------------------------"

        if [ -z "$UNIQUE_COMMITS" ]
        then
          echo "any=false" >> "$GITHUB_OUTPUT"
            echo "no *.py files changes matched"
            exit 0
        fi

        FILES="$(
          for c in $UNIQUE_COMMITS
          do
            git diff --name-only --diff-filter=ACMRDT "${c}^!" || true
          done | tr -d '\r' | sort -u 
        )"

        PY_CHANGED="$(printf '%s\n' "$FILES" | grep -Ei '\.py$' || true)"
        # multi-line output
        echo "list<<EOF" >> GITHUB_OUTPUT
        echo "${PY_CHANGED}" >> GITHUB_OUTPUT
        echo "EOF" >> GITHUB_OUTPUT

        if [ -n "$PY_CHANGED"]
        then
          echo "any=true" >> "$GITHUB_OUTPUT"
          echo "Matched python files:"
          echo "$PY_CHANGED"
        else
          echo "any=false" >> "$GITHUB_OUTPUT"
        fi