name: Detect Python changes
description: Outputs whether *.py files changed and their list
outputs:
  any:
    description: "true/false if any matched files changed"
    value: ${{ steps.detect.outputs.any }}
  list:
    description: "newline-separated list of changed *.py files"
    value: ${{ steps.detect.outputs.list }}
runs:
  using: "composite"
  steps:
    - name: Checkout (full history)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - id: detect
      shell: bash
      run: |
        set -euo pipefail

        HEAD_SHA="${{ github.sha }}"
        DEFAULT_BRANCH="${{ github.event.repository.default_branch || 'main' }}"

        git fetch --no-tags --prune origin "$DEFAULT_BRANCH" --depth=1 origin "+refs/heads/${DEFAULT_BRANCH}:refs/remotes/origin/${DEFAULT_BRANCH}"

        BASE_SHA="$(git merge-base "origin/${DEFAULT_BRANCH}" "${HEAD_SHA}")"

        
        echo "-------DEBUG (detector)--------"
        echo "DEFAULT_BRANCH: ${DEFAULT_BRANCH}"
        echo "HEAD_SHA: ${HEAD_SHA}"
        echo "BASE_SHA: ${BASE_SHA}"
        echo "RANGE: ${BASE_SHA}..${HEAD_SHA}"
        echo "name status:"
        git diff --name-status "${BASE_SHA}..${HEAD_SHA}" || true
        echo "-------------------------------"

        CHANGED_ALL="$(
          git diff --name-only --diff-filter=ACMRDT "${BASE_SHA}..${HEAD_SHA}" | tr -d '\r' | sort -u
        )"

        PY_CHANGED="$(printf '%s\n' "$CHANGED_ALL" | grep -Ei '\.py$' || true)"
        # multi-line output
        echo "list<<EOF" >> GITHUB_OUTPUT
        echo "${PY_CHANGED}" >> GITHUB_OUTPUT
        echo "EOF" >> GITHUB_OUTPUT

        if [ -n "$PY_CHANGED"]
        then
          echo "any=true" >> "$GITHUB_OUTPUT"
          echo "Matched python files:"
          echo "$PY_CHANGED"
        else
          echo "any=false" >> "$GITHUB_OUTPUT"
        fi