name: Detect Python and HTML changes
description: Outputs whether *.py or HTML files changed and their list
outputs:
  any:
    description: "true/false if any matched files changed"
    value: ${{ steps.detect.outputs.any }}
  list:
    description: "newline-separated list of changed *.py and HTML files"
    value: ${{ steps.detect.outputs.list }}
runs:
  using: "composite"
  steps:
    - name: Checkout (full history)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    
    - id: detect
      shell: bash
      run: |
        set -euo pipefail

        DEFAULT_BRANCH="${{ github.event.repository.default_branch || 'main' }}"

        git fetch --no-tags --depth=2 origin "${DEFAULT_BRANCH}"

        echo "DEBUG - HEAD_SHA: $(git rev-parse HEAD)"

        BASE_SHA="$(git merge-base "origin/${DEFAULT_BRANCH}" HEAD)"
        
        CURRENT_BRANCH="$(git branch --show-current)"

        if [ "$CURRENT_BRANCH" = "$DEFAULT_BRANCH" ]
        then
          COMPARE_SHA="$(git rev-parse HEAD^)"
        else
          COMPARE_SHA=${BASE_SHA}
        fi

        echo "-------DEBUG (detector)--------"
        echo "BASE_SHA: ${BASE_SHA}, HEAD=$(git rev-parse HEAD)"
        echo "COMPARE_SHA: ${COMPARE_SHA}, CURRENT_BRANCH=${CURRENT_BRANCH}"
        git diff --name-status "${COMPARE_SHA}..HEAD"
        echo "-------------------------------"

        ###########################
        # CHANGED_ALL shows every file different between my branch's HEAD and the merge-base with main.
        # MATCHED_CHANGES includes all python and HTML files changed when you merge main into your branch. 
        ###########################
        CHANGED_ALL="$(git diff --name-only --diff-filter=ACMRDT "${COMPARE_SHA}..HEAD" | tr -d '\r' | sort -u)"
        MATCHED_CHANGES="$(printf '%s\n' "$CHANGED_ALL" | grep -Ei '\.(py|html)$' || true)"
        
        # multi-line output
        echo "list<<EOF" >> "$GITHUB_OUTPUT"
        printf '%s\n' "$MATCHED_CHANGES" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        if [ -n "$MATCHED_CHANGES" ]
        then
          echo "any=true" >> "$GITHUB_OUTPUT"
          echo "Matched python and HTML files:"
          echo "$MATCHED_CHANGES"
        else
          echo "any=false" >> "$GITHUB_OUTPUT"
          
        fi