# Generated by Django 4.1.3 on 2022-12-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0002_domain_host_nameserver_hostip_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domainapplication",
            old_name="is_election_office",
            new_name="is_election_board",
        ),
        migrations.RenameField(
            model_name="domainapplication",
            old_name="acknowledged_policy",
            new_name="is_policy_acknowledged",
        ),
        migrations.RenameField(
            model_name="domainapplication",
            old_name="zip_code",
            new_name="zipcode",
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="federal_branch",
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="street_address",
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="unit_number",
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="unit_type",
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="address_line1",
            field=models.TextField(blank=True, help_text="Address line 1", null=True),
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="address_line2",
            field=models.CharField(blank=True, help_text="Address line 2", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="federal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("executive", "Executive"),
                    ("judicial", "Judicial"),
                    ("legislative", "Legislative"),
                ],
                help_text="Branch of federal government",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federal", "Federal: a federal agency"),
                    ("interstate", "Interstate: an organization of two or more states"),
                    (
                        "state_or_territory",
                        "State or Territory: One of the 50 U.S. states, the District of Columbia, American Samoa, Guam, Northern Mariana Islands, Puerto Rico, or the U.S. Virgin Islands",
                    ),
                    (
                        "tribal",
                        "Tribal: a tribal government recognized by the federal or state government",
                    ),
                    ("county", "County: a county, parish, or borough"),
                    ("city", "City: a city, town, township, village, etc."),
                    (
                        "special_district",
                        "Special District: an independent organization within a single state",
                    ),
                ],
                help_text="Type of Organization",
                max_length=255,
                null=True,
            ),
        ),
    ]
