# Generated by Django 4.1.3 on 2022-12-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registrar",
            "0003_rename_is_election_office_domainapplication_is_election_board_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="domainapplication",
            name="federal_agency",
            field=models.TextField(help_text="Top level federal agency", null=True),
        ),
    ]
