# Generated by Django 4.1.4 on 2022-12-12 20:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0004_domainapplication_federal_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                help_text="Phone",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
    ]
