# Generated by Django 4.1.3 on 2022-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0005_domainapplication_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="federal_agency",
            field=models.TextField(
                blank=True, help_text="Top level federal agency", null=True
            ),
        ),
    ]
