# Generated by Django 4.1.5 on 2023-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0009_domainapplication_federally_recognized_tribe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainapplication",
            name="no_other_contacts_rationale",
            field=models.TextField(
                blank=True,
                help_text="Reason for listing no additional contacts",
                null=True,
            ),
        ),
    ]
