# Generated by Django 4.1.6 on 2023-02-27 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0010_domainapplication_no_other_contacts_rationale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainapplication",
            name="security_email",
        ),
    ]
