# Generated by Django 4.1.6 on 2023-03-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0011_remove_domainapplication_security_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
