# Generated by Django 4.1.6 on 2023-03-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0012_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("registrant", "Registrant"),
                            ("administrative", "Administrative"),
                            ("technical", "Technical"),
                            ("security", "Security"),
                        ],
                        max_length=14,
                    ),
                ),
                ("name", models.TextField()),
                ("org", models.TextField(null=True)),
                ("street1", models.TextField()),
                ("street2", models.TextField(null=True)),
                ("street3", models.TextField(null=True)),
                ("city", models.TextField()),
                ("sp", models.TextField()),
                ("pc", models.TextField()),
                ("cc", models.TextField()),
                ("email", models.TextField()),
                ("voice", models.TextField()),
                ("fax", models.TextField(null=True)),
                ("pw", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
