# Generated by Django 4.1.6 on 2023-03-07 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields  # type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0013_publiccontact_contact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                help_text="Phone",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
    ]
