# Generated by Django 4.1.6 on 2023-03-10 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0014_user_phone_alter_contact_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="owners",
        ),
        migrations.CreateModel(
            name="UserDomainRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.TextField(choices=[("admin", "Admin")])),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="registrar.domain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="domains",
            field=models.ManyToManyField(
                related_name="users",
                through="registrar.UserDomainRole",
                to="registrar.domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdomainrole",
            constraint=models.UniqueConstraint(fields=("user", "domain"), name="unique_user_domain_role"),
        ),
    ]
