# Generated by Django 4.1.6 on 2023-05-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0017_alter_domainapplication_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainInformation",
            fields=[
                (
                    "domainapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="registrar.domainapplication",
                    ),
                ),
                (
                    "security_email",
                    models.EmailField(
                        blank=True,
                        help_text="Security email for public use",
                        max_length=320,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("registrar.domainapplication",),
        ),
    ]
