# Generated by Django 4.1.6 on 2023-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0018_domaininformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "federal",
                        "Federal: an agency of the U.S. government's executive, legislative, or judicial branches",
                    ),
                    ("interstate", "Interstate: an organization of two or more states"),
                    (
                        "state_or_territory",
                        "State or territory: one of the 50 U.S. states, the District of Columbia, American Samoa, Guam, Northern Mariana Islands, Puerto Rico, or the U.S. Virgin Islands",
                    ),
                    (
                        "tribal",
                        "Tribal: a tribal government recognized by the federal or a state government",
                    ),
                    ("county", "County: a county, parish, or borough"),
                    ("city", "City: a city, town, township, village, etc."),
                    (
                        "special_district",
                        "Special district: an independent organization within a single state",
                    ),
                    (
                        "school_district",
                        "School district: a school district that is not part of a local government",
                    ),
                ],
                help_text="Type of organization",
                max_length=255,
                null=True,
            ),
        ),
    ]
