# Generated by Django 4.2.1 on 2023-05-11 17:43
# mypy: ignore-errors

from django.db import migrations, models
import django.db.models.deletion
import registrar.models.public_contact
import registrar.models.utility.domain_field
import registrar.models.utility.domain_helper


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0019_alter_domainapplication_organization_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="Fully qualified domain name",
                        max_length=253,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, registrar.models.utility.domain_helper.DomainHelper),
        ),
        migrations.RemoveConstraint(
            model_name="domain",
            name="unique_domain_name_in_registry",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="is_active",
        ),
        migrations.AddField(
            model_name="domain",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("deleted", "Deleted"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
            ),
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="approved_domain",
            field=models.OneToOneField(
                blank=True,
                help_text="The approved domain",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domain_application",
                to="registrar.domain",
            ),
        ),
        migrations.AddField(
            model_name="publiccontact",
            name="domain",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="registrar.domain",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publiccontact",
            name="has_edits",
            field=models.BooleanField(
                default=True,
                help_text="Whether edits have been made since last published",
            ),
        ),
        migrations.AddField(
            model_name="publiccontact",
            name="registry_id",
            field=models.CharField(
                default=registrar.models.public_contact.get_id,
                help_text="Auto generated ID to track this contact in the registry",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=registrar.models.utility.domain_field.DomainField(
                default=None,
                help_text="Fully qualified domain name",
                max_length=253,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="domain",
            field=models.ForeignKey(
                help_text="Domain to which this host belongs",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hosts",
                to="registrar.domain",
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="cc",
            field=models.TextField(help_text="Contact's country code"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="city",
            field=models.TextField(help_text="Contact's city"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("registrant", "Registrant"),
                    ("administrative", "Administrative"),
                    ("technical", "Technical"),
                    ("security", "Security"),
                ],
                help_text="For which type of WHOIS contact",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="email",
            field=models.TextField(help_text="Contact's email address"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="fax",
            field=models.TextField(
                help_text="Contact's fax number (null ok). Must be in ITU.E164.2005 format.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="name",
            field=models.TextField(help_text="Contact's full name"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="org",
            field=models.TextField(
                help_text="Contact's organization (null ok)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="pc",
            field=models.TextField(help_text="Contact's postal code"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="pw",
            field=models.TextField(
                help_text="Contact's authorization code. 16 characters minimum."
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="sp",
            field=models.TextField(help_text="Contact's state or province"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="street1",
            field=models.TextField(help_text="Contact's street"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="street2",
            field=models.TextField(help_text="Contact's street (null ok)", null=True),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="street3",
            field=models.TextField(help_text="Contact's street (null ok)", null=True),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="voice",
            field=models.TextField(
                help_text="Contact's phone number. Must be in ITU.E164.2005 format"
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="requested_domain",
            field=models.OneToOneField(
                blank=True,
                help_text="The requested domain",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domain_application",
                to="registrar.draftdomain",
            ),
        ),
    ]
