# Generated by Django 4.2 on 2023-05-17 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0019_alter_domainapplication_organization_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domaininformation",
            name="security_email",
        ),
    ]
