# Generated by Django 4.2.1 on 2023-05-25 15:03

from django.db import migrations, models
import django.db.models.deletion
import registrar.models.public_contact


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0020_remove_domaininformation_security_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="publiccontact",
            name="domain",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="registrar.domain",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publiccontact",
            name="registry_id",
            field=models.CharField(
                default=registrar.models.public_contact.get_id,
                help_text="Auto generated ID to track this contact in the registry",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="cc",
            field=models.TextField(help_text="Contact's country code"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="city",
            field=models.TextField(help_text="Contact's city"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("registrant", "Registrant"),
                    ("administrative", "Administrative"),
                    ("technical", "Technical"),
                    ("security", "Security"),
                ],
                help_text="For which type of WHOIS contact",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="email",
            field=models.TextField(help_text="Contact's email address"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="fax",
            field=models.TextField(
                help_text="Contact's fax number (null ok). Must be in ITU.E164.2005 format.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="name",
            field=models.TextField(help_text="Contact's full name"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="org",
            field=models.TextField(help_text="Contact's organization (null ok)", null=True),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="pc",
            field=models.TextField(help_text="Contact's postal code"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="pw",
            field=models.TextField(help_text="Contact's authorization code. 16 characters minimum."),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="sp",
            field=models.TextField(help_text="Contact's state or province"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="street1",
            field=models.TextField(help_text="Contact's street"),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="street2",
            field=models.TextField(help_text="Contact's street (null ok)", null=True),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="street3",
            field=models.TextField(help_text="Contact's street (null ok)", null=True),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="voice",
            field=models.TextField(help_text="Contact's phone number. Must be in ITU.E164.2005 format"),
        ),
    ]
