# Generated by Django 4.2.1 on 2023-05-26 19:21

from django.db import migrations, models
import registrar.models.utility.domain_field


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0022_draftdomain_domainapplication_approved_domain_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="domain",
            name="unique_domain_name_in_registry",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="is_active",
        ),
        migrations.AddField(
            model_name="domain",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("deleted", "Deleted"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=registrar.models.utility.domain_field.DomainField(
                default=None,
                help_text="Fully qualified domain name",
                max_length=253,
                unique=True,
            ),
        ),
    ]
