# Generated by Django 4.1.6 on 2023-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0022_draftdomain_domainapplication_approved_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="address_line2",
            field=models.TextField(
                blank=True, help_text="Street address line 2", null=True
            ),
        ),
    ]
