# Generated by Django 4.2.1 on 2023-06-01 21:47

from django.db import migrations
import django_fsm  # type: ignore
import registrar.models.utility.domain_field


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0024_alter_contact_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="domain",
            name="unique_domain_name_in_registry",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="is_active",
        ),
        migrations.AddField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("created", "Created"),
                    ("deleted", "Deleted"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=registrar.models.utility.domain_field.DomainField(
                default=None,
                help_text="Fully qualified domain name",
                max_length=253,
                unique=True,
            ),
        ),
    ]
