# Generated by Django 4.2.1 on 2023-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0025_remove_domain_unique_domain_name_in_registry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="address_line2",
            field=models.TextField(blank=True, help_text="Street address line 2", null=True),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="address_line2",
            field=models.TextField(blank=True, help_text="Street address line 2", null=True),
        ),
    ]
