# Generated by Django 4.2.2 on 2023-07-12 21:31
# Generated by Django 4.2.2 on 2023-07-13 17:56
# hand merged

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0027_alter_domaininformation_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "started"),
                    ("submitted", "submitted"),
                    ("in review", "in review"),
                    ("action needed", "action needed"),
                    ("approved", "approved"),
                    ("withdrawn", "withdrawn"),
                    ("rejected", "rejected"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
