# Generated by Django 4.2.1 on 2023-08-18 16:59

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0028_alter_domainapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("ineligible", "ineligible")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "started"),
                    ("submitted", "submitted"),
                    ("in review", "in review"),
                    ("action needed", "action needed"),
                    ("approved", "approved"),
                    ("withdrawn", "withdrawn"),
                    ("rejected", "rejected"),
                    ("ineligible", "ineligible"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
