# Generated by Django 4.2.1 on 2023-08-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0029_user_status_alter_domainapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("restricted", "restricted")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
