# Generated by Django 4.2.1 on 2023-09-11 12:44

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0030_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("unknown", "Unknown"),
                    ("dns needed", "Dns Needed"),
                    ("ready", "Ready"),
                    ("client hold", "On Hold"),
                    ("deleted", "Deleted"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("registrant", "Registrant"),
                    ("admin", "Administrative"),
                    ("tech", "Technical"),
                    ("security", "Security"),
                ],
                help_text="For which type of WHOIS contact",
                max_length=14,
            ),
        ),
    ]
