# Generated by Django 4.2.1 on 2023-09-15 21:05

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0030_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("unknown", "Unknown"),
                    ("dns needed", "Dns Needed"),
                    ("ready", "Ready"),
                    ("on hold", "On Hold"),
                    ("deleted", "Deleted"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
                protected=True,
            ),
        ),
        migrations.CreateModel(
            name="TransitionDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.TextField(
                        help_text="Username - this will be an email address",
                        verbose_name="Username",
                    ),
                ),
                (
                    "domain_name",
                    models.TextField(blank=True, null=True, verbose_name="Domain name"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("created", "Created"), ("hold", "Hold")],
                        help_text="domain status during the transfer",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="indicates whether email was sent",
                        verbose_name="email sent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="more_organization_information",
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="type_of_work",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="more_organization_information",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="type_of_work",
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="about_your_organization",
            field=models.TextField(blank=True, help_text="Information about your organization", null=True),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="about_your_organization",
            field=models.TextField(blank=True, help_text="Information about your organization", null=True),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="approved_domain",
            field=models.OneToOneField(
                blank=True,
                help_text="The approved domain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_application",
                to="registrar.domain",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="domain",
            field=models.OneToOneField(
                blank=True,
                help_text="Domain to which this information belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_info",
                to="registrar.domain",
            ),
        ),
        migrations.AlterField(
            model_name="publiccontact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("registrant", "Registrant"),
                    ("admin", "Administrative"),
                    ("tech", "Technical"),
                    ("security", "Security"),
                ],
                help_text="For which type of WHOIS contact",
                max_length=14,
            ),
        ),
    ]
