# Generated by Django 4.2.1 on 2023-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0030_alter_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainapplication",
            name="more_organization_information",
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="type_of_work",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="more_organization_information",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="type_of_work",
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="about_your_organization",
            field=models.TextField(
                blank=True, help_text="Information about your organization", null=True
            ),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="about_your_organization",
            field=models.TextField(
                blank=True, help_text="Information about your organization", null=True
            ),
        ),
    ]
