# Generated by Django 4.2.1 on 2023-09-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0030_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="approved_domain",
            field=models.OneToOneField(
                blank=True,
                help_text="The approved domain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_application",
                to="registrar.domain",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="domain",
            field=models.OneToOneField(
                blank=True,
                help_text="Domain to which this information belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_info",
                to="registrar.domain",
            ),
        ),
    ]
