# Generated by Django 4.2.1 on 2023-09-07 17:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0030_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("created", "Created"),
                    ("deleted", "Deleted"),
                    ("unknown", "Unknown"),
                    ("ready", "Ready"),
                    ("onhold", "Onhold"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
                protected=True,
            ),
        ),
    ]
