# Generated by Django 4.2.1 on 2023-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0030_alter_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitionDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.TextField(
                        help_text="Username - this will be an email address",
                        verbose_name="Username",
                    ),
                ),
                (
                    "domain_name",
                    models.TextField(blank=True, null=True, verbose_name="Domain name"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("created", "Created"), ("hold", "Hold")],
                        help_text="domain status during the transfer",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "ignoreServerHold",
                    models.BooleanField(
                        default=False,
                        help_text="specifies whether to ignore server hold",
                        verbose_name="ignore Server Hold",
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="indicates whether email was sent",
                        verbose_name="email sent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
