# Generated by Django 4.2.1 on 2023-09-12 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0031_alter_domain_state"),
        ("registrar", "0031_transitiondomain"),
    ]

    operations = []
