# Generated by Django 4.2.1 on 2023-09-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0032_merge_0031_alter_domain_state_0031_transitiondomain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainapplication",
            name="more_organization_information",
        ),
        migrations.RemoveField(
            model_name="domainapplication",
            name="type_of_work",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="more_organization_information",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="type_of_work",
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="about_your_organization",
            field=models.TextField(
                blank=True, help_text="Information about your organization", null=True
            ),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="about_your_organization",
            field=models.TextField(
                blank=True, help_text="Information about your organization", null=True
            ),
        ),
    ]
