# Generated by Django 4.2.1 on 2023-09-13 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "registrar",
            "0031_remove_domainapplication_more_organization_information_and_more",
        ),
        ("registrar", "0032_merge_0031_alter_domain_state_0031_transitiondomain"),
    ]

    operations = []
