# Generated by Django 4.2.1 on 2023-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0032_alter_transitiondomain_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="dnssec_enabled",
            field=models.BooleanField(
                default=False, help_text="Boolean indicating if dnssec is enabled"
            ),
        ),
    ]
