# Generated by Django 4.2.1 on 2023-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0033_domain_dnssec_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="dnssec_ds_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Boolean indicating if DS record adding is confirmed",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="dnssec_key_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Boolean indicating if Key record adding is confirmed",
            ),
        ),
    ]
