# Generated by Django 4.2.1 on 2023-09-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0034_usergroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("analyst_access_permission", "Analyst Access Permission"),
                    ("full_access_permission", "Full Access Permission"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federal", "Federal"),
                    ("interstate", "Interstate"),
                    ("state_or_territory", "State or territory"),
                    ("tribal", "Tribal"),
                    ("county", "County"),
                    ("city", "City"),
                    ("special_district", "Special district"),
                    ("school_district", "School district"),
                ],
                help_text="Type of organization",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federal", "Federal"),
                    ("interstate", "Interstate"),
                    ("state_or_territory", "State or territory"),
                    ("tribal", "Tribal"),
                    ("county", "County"),
                    ("city", "City"),
                    ("special_district", "Special district"),
                    ("school_district", "School district"),
                ],
                help_text="Type of Organization",
                max_length=255,
                null=True,
            ),
        ),
    ]
