# Generated by Django 4.2.1 on 2023-10-13 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0038_alter_domainapplication_organization_type_and_more"),
        ("registrar", "0038_create_groups_v02"),
    ]

    operations = []
