# Generated by Django 4.2.1 on 2023-10-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0039_alter_transitiondomain_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomainrole",
            name="role",
            field=models.TextField(choices=[("manager", "Manager")]),
        ),
    ]
