# Generated by Django 4.2.1 on 2023-10-18 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0039_alter_transitiondomain_status"),
        ("registrar", "0039_merge_20231013_2029"),
    ]

    operations = []
