# Generated by Django 4.2.1 on 2023-10-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0040_alter_userdomainrole_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federal", "Federal"),
                    ("interstate", "Interstate"),
                    ("state_or_territory", "State or territory"),
                    ("tribal", "Tribal"),
                    ("county", "County"),
                    ("city", "City"),
                    ("special_district", "Special district"),
                    ("school_district", "School district"),
                ],
                help_text="Type of organization",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federal", "Federal"),
                    ("interstate", "Interstate"),
                    ("state_or_territory", "State or territory"),
                    ("tribal", "Tribal"),
                    ("county", "County"),
                    ("city", "City"),
                    ("special_district", "Special district"),
                    ("school_district", "School district"),
                ],
                help_text="Type of Organization",
                max_length=255,
                null=True,
            ),
        ),
    ]
