# Generated by Django 4.2.6 on 2023-10-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0043_transitiondomain_federal_agency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitiondomain",
            name="organization_name",
            field=models.TextField(
                blank=True, help_text="Organization name", null=True
            ),
        ),
    ]
