# Generated by Django 4.2.1 on 2023-10-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0043_domain_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitiondomain",
            name="federal_agency",
            field=models.TextField(blank=True, help_text="Federal agency", null=True),
        ),
        migrations.AddField(
            model_name="transitiondomain",
            name="federal_type",
            field=models.TextField(
                blank=True,
                help_text="Federal government branch",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transitiondomain",
            name="organization_type",
            field=models.TextField(
                blank=True, help_text="Type of organization", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="transitiondomain",
            name="organization_name",
            field=models.TextField(
                blank=True, db_index=True, help_text="Organization name", null=True
            ),
        ),
    ]
