# Generated by Django 4.2.7 on 2023-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0046_transitiondomain_email_transitiondomain_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitiondomain",
            name="address_line",
            field=models.TextField(blank=True, help_text="Street address", null=True),
        ),
        migrations.AddField(
            model_name="transitiondomain",
            name="city",
            field=models.TextField(blank=True, help_text="City", null=True),
        ),
        migrations.AddField(
            model_name="transitiondomain",
            name="state_territory",
            field=models.CharField(blank=True, help_text="State, territory, or military post", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="transitiondomain",
            name="zipcode",
            field=models.CharField(blank=True, db_index=True, help_text="Zip code", max_length=10, null=True),
        ),
    ]
