# Generated by Django 4.2.7 on 2023-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0049_alter_domainapplication_current_websites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="middle_name",
            field=models.TextField(blank=True, help_text="Middle name (optional)", null=True),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="address_line2",
            field=models.TextField(blank=True, help_text="Street address line 2 (optional)", null=True),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="address_line2",
            field=models.TextField(
                blank=True,
                help_text="Street address line 2 (optional)",
                null=True,
                verbose_name="Street address line 2 (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="middle_name",
            field=models.TextField(blank=True, help_text="Middle name (optional)", null=True),
        ),
    ]
