# Generated by Django 4.2.7 on 2023-12-05 21:21

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0050_alter_transitiondomain_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("unknown", "Unknown"),
                    ("dns needed", "Dns needed"),
                    ("ready", "Ready"),
                    ("on hold", "On hold"),
                    ("deleted", "Deleted"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
                protected=True,
            ),
        ),
    ]
