# Generated by Django 4.2.7 on 2023-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0050_alter_domainapplication_anything_else_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitiondomain",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("ready", "Ready"), ("on hold", "On Hold"), ("unknown", "Unknown")],
                default="ready",
                help_text="domain status during the transfer",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
