# Generated by Django 4.2.7 on 2023-11-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0051_alter_domainapplication_urbanization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="anything_else",
            field=models.TextField(blank=True, help_text="Anything else?", null=True),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="anything_else",
            field=models.TextField(blank=True, help_text="Anything else?", null=True),
        ),
    ]
