# Generated by Django 4.2.7 on 2023-12-05 21:25

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0051_alter_domain_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "Started"),
                    ("submitted", "Submitted"),
                    ("in review", "In review"),
                    ("action needed", "Action needed"),
                    ("approved", "Approved"),
                    ("withdrawn", "Withdrawn"),
                    ("rejected", "Rejected"),
                    ("ineligible", "Ineligible"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
