# Generated by Django 4.2.7 on 2023-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0053_create_groups_v05"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitiondomain",
            name="processed",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this TransitionDomain was already processed",
                verbose_name="Processed",
            ),
        ),
    ]
