# Generated by Django 4.2.7 on 2023-12-05 23:14

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0053_alter_domain_state_alter_domainapplication_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "Started"),
                    ("submitted", "Submitted"),
                    ("in_review", "In review"),
                    ("action_needed", "Action needed"),
                    ("approved", "Approved"),
                    ("withdrawn", "Withdrawn"),
                    ("rejected", "Rejected"),
                    ("ineligible", "Ineligible"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
