# Generated by Django 4.2.7 on 2023-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0054_alter_domainapplication_federal_agency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitiondomain",
            name="processed",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this TransitionDomain was already processed",
                verbose_name="Processed",
            ),
        ),
    ]
