# Generated by Django 4.2.7 on 2023-12-06 16:16

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0055_transitiondomain_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("unknown", "Unknown"),
                    ("dns needed", "Dns needed"),
                    ("ready", "Ready"),
                    ("on hold", "On hold"),
                    ("deleted", "Deleted"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "Started"),
                    ("submitted", "Submitted"),
                    ("in review", "In review"),
                    ("action needed", "Action needed"),
                    ("approved", "Approved"),
                    ("withdrawn", "Withdrawn"),
                    ("rejected", "Rejected"),
                    ("ineligible", "Ineligible"),
                ],
                default="started",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="domaininvitation",
            name="status",
            field=django_fsm.FSMField(
                choices=[("invited", "Invited"), ("retrieved", "Retrieved")],
                default="invited",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("ready", "Ready"), ("on hold", "On hold"), ("unknown", "Unknown")],
                default="ready",
                help_text="domain status during the transfer",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
