# Generated by Django 4.2.7 on 2023-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0056_alter_domain_state_alter_DomainRequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="DomainRequest",
            name="submission_date",
            field=models.DateField(blank=True, default=None, help_text="Date submitted", null=True),
        ),
    ]
