# Generated by Django 4.2.7 on 2023-12-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0056_alter_domain_state_alter_domainapplication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="deleted_at",
            field=models.DateField(editable=False, help_text="Deleted at date", null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="ready_at",
            field=models.DateField(
                editable=False, help_text="The last time this domain moved into the READY state", null=True
            ),
        ),
    ]
