# Generated by Django 4.2.7 on 2023-12-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0057_domainapplication_submission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="deleted_at",
            field=models.DateField(editable=False, help_text="Deleted at date", null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="first_ready_at",
            field=models.DateField(
                editable=False, help_text="The last time this domain moved into the READY state", null=True
            ),
        ),
    ]
