# Generated by Django 4.2.7 on 2023-12-27 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0057_domainapplication_submission_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domaininformation",
            options={"verbose_name_plural": "Domain information"},
        ),
    ]
