# Generated by Django 4.2.7 on 2023-12-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0058_alter_domaininformation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="deleted",
            field=models.DateField(editable=False, help_text="Deleted at date", null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="first_ready",
            field=models.DateField(
                editable=False, help_text="The last time this domain moved into the READY state", null=True
            ),
        ),
    ]
