# Generated by Django 4.2.7 on 2024-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0061_domain_security_contact_registry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(default=None, help_text="Fully qualified domain name", max_length=253),
        ),
    ]
