# Generated by Django 4.2.7 on 2024-01-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0062_alter_host_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftdomain",
            name="is_incomplete",
            field=models.BooleanField(default=False, help_text="Determines if this Draft is complete or not"),
        ),
        migrations.AlterField(
            model_name="draftdomain",
            name="name",
            field=models.CharField(help_text="Fully qualified domain name", max_length=253),
        ),
    ]
