# Generated by Django 4.2.7 on 2024-01-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0062_alter_host_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftdomain",
            name="is_complete",
            field=models.BooleanField(default=True, help_text="Determines if this Draft is complete or not"),
        ),
    ]
