# Generated by Django 4.2.7 on 2024-01-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0063_veryimportantperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="address_line1",
            field=models.TextField(blank=True, help_text="Street address", null=True, verbose_name="Address line 1"),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="address_line2",
            field=models.TextField(
                blank=True, help_text="Street address line 2 (optional)", null=True, verbose_name="Address line 2"
            ),
        ),
    ]
