# Generated by Django 4.2.7 on 2024-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0064_alter_domainapplication_address_line1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about this domain", null=True),
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about this request", null=True),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about the request", null=True),
        ),
    ]
