# Generated by Django 4.2.7 on 2024-01-29 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0065_create_groups_v06"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VeryImportantPerson",
            new_name="VerifiedByStaff",
        ),
        migrations.AlterModelOptions(
            name="verifiedbystaff",
            options={"verbose_name_plural": "Verified by staff"},
        ),
    ]
