# Generated by Django 4.2.7 on 2024-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0067_create_groups_v07"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainapplication",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about this request", null=True),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about the request", null=True),
        ),
    ]
