# Generated by Django 4.2.7 on 2024-02-14 21:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0068_domainapplication_notes_domaininformation_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name="first name / given name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name="last name / family name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="middle_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, db_index=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="title or role in your organization"),
        ),
    ]
