# Generated by Django 4.2.7 on 2024-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0069_alter_contact_email_alter_contact_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainapplication",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                choices=[
                    ("domain_purpose", "Domain purpose requirements not met"),
                    ("requestor", "Requestor isn't authorized to make the request"),
                    (
                        "second_domain_reasoning",
                        "Organization already has a domain and does not provide sufficient reasoning for a second domain",
                    ),
                    (
                        "contacts_or_organization_legitimacy",
                        "Research could not corroborate legitimacy of contacts or organization",
                    ),
                    ("organization_eligibility", "Organization isn't eligible for a .gov"),
                    ("naming_requirements", "Naming requirements not met"),
                ],
                null=True,
            ),
        ),
    ]
