# Generated by Django 4.2.10 on 2024-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0072_alter_publiccontact_fax_alter_publiccontact_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="current_websites",
            field=models.ManyToManyField(
                blank=True, related_name="current+", to="registrar.website", verbose_name="Current websites"
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="other_contacts",
            field=models.ManyToManyField(
                blank=True, related_name="contact_applications", to="registrar.contact", verbose_name="Other employees"
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="other_contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="contact_applications_information",
                to="registrar.contact",
                verbose_name="Other employees",
            ),
        ),
    ]
