# Generated by Django 4.2.10 on 2024-03-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0072_alter_publiccontact_fax_alter_publiccontact_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainapplication",
            name="approved_domain",
            field=models.OneToOneField(
                blank=True,
                help_text="The approved domain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_request",
                to="registrar.domain",
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domain_requests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="investigator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_requests_investigating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="other_contacts",
            field=models.ManyToManyField(
                blank=True, related_name="contact_domain_requests", to="registrar.contact", verbose_name="contacts"
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="requested_domain",
            field=models.OneToOneField(
                blank=True,
                help_text="The requested domain",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domain_request",
                to="registrar.draftdomain",
            ),
        ),
        migrations.AlterField(
            model_name="domainapplication",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_domain_requests",
                to="registrar.contact",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="domain_application",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated domain request",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="DomainRequest_info",
                to="registrar.domainapplication",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="other_contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="contact_domain_requests_information",
                to="registrar.contact",
                verbose_name="contacts",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_domain_requests_information",
                to="registrar.contact",
            ),
        ),
    ]
