# Generated by Django 4.2.7 on 2024-01-29 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrar", "0072_alter_publiccontact_fax_alter_publiccontact_voice"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DomainApplication",
            new_name="DomainRequest",
        )
    ]
