# Generated by Django 4.2.10 on 2024-03-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0073_alter_domainapplication_approved_domain_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DomainApplication",
            new_name="DomainRequest",
        ),
        migrations.RenameField(
            model_name="domaininformation",
            old_name="domain_application",
            new_name="domain_request",
        ),
    ]
