# Generated by Django 4.2.10 on 2024-03-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0076_alter_domainrequest_current_websites_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederalAgency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agency", models.CharField(blank=True, help_text="Federal agency", null=True)),
            ],
            options={
                "verbose_name": "Federal agency",
                "verbose_name_plural": "Federal agencies",
            },
        ),
    ]
