# Generated by Django 4.2.10 on 2024-04-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0081_create_groups_v10"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="cisa_representative_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="cisa_representative_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
