# Generated by Django 4.2.10 on 2024-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0081_create_groups_v10"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=320, null=True),
        ),
    ]
