# Generated by Django 4.2.10 on 2024-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0084_create_groups_v11"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="cisa_representative_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=320, null=True, verbose_name="CISA region representative"
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="cisa_representative_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=320, null=True, verbose_name="CISA region representative"
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="anything_else",
            field=models.TextField(
                blank=True, help_text="Anything else?", null=True, verbose_name="Additional Details"
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="anything_else",
            field=models.TextField(
                blank=True, help_text="Anything else?", null=True, verbose_name="Additional Details"
            ),
        ),
    ]
