# Generated by Django 4.2.10 on 2024-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0084_create_groups_v11"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("grandfathered", "Legacy user"),
                    ("verified_by_staff", "Verified by staff"),
                    ("regular", "Verified by Login.gov"),
                    ("invited", "Invited by a domain manager"),
                ],
                help_text="The means through which this user was verified",
                null=True,
            ),
        ),
    ]
