# Generated by Django 4.2.10 on 2024-04-18 18:01

import django.core.validators
from django.db import migrations, models
import django_fsm
import registrar.models.utility.domain_field


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0084_create_groups_v11"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, db_index=True, null=True, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, db_index=True, null=True, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.CharField(blank=True, null=True, verbose_name="title / role"),
        ),
        migrations.AlterField(
            model_name="domain",
            name="deleted",
            field=models.DateField(editable=False, help_text="Deleted at date", null=True, verbose_name="deleted on"),
        ),
        migrations.AlterField(
            model_name="domain",
            name="first_ready",
            field=models.DateField(
                editable=False,
                help_text="The last time this domain moved into the READY state",
                null=True,
                verbose_name="first ready on",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=registrar.models.utility.domain_field.DomainField(
                default=None,
                help_text="Fully qualified domain name",
                max_length=253,
                unique=True,
                verbose_name="domain",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("unknown", "Unknown"),
                    ("dns needed", "Dns needed"),
                    ("ready", "Ready"),
                    ("on hold", "On hold"),
                    ("deleted", "Deleted"),
                ],
                default="unknown",
                help_text="Very basic info about the lifecycle of this domain object",
                max_length=21,
                protected=True,
                verbose_name="domain state",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="address_line1",
            field=models.CharField(blank=True, help_text="Street address", null=True, verbose_name="address line 1"),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="address_line2",
            field=models.CharField(
                blank=True, help_text="Street address line 2 (optional)", null=True, verbose_name="address line 2"
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="is_election_board",
            field=models.BooleanField(
                blank=True,
                help_text="Is your organization an election office?",
                null=True,
                verbose_name="election office",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="state_territory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama (AL)"),
                    ("AK", "Alaska (AK)"),
                    ("AS", "American Samoa (AS)"),
                    ("AZ", "Arizona (AZ)"),
                    ("AR", "Arkansas (AR)"),
                    ("CA", "California (CA)"),
                    ("CO", "Colorado (CO)"),
                    ("CT", "Connecticut (CT)"),
                    ("DE", "Delaware (DE)"),
                    ("DC", "District of Columbia (DC)"),
                    ("FL", "Florida (FL)"),
                    ("GA", "Georgia (GA)"),
                    ("GU", "Guam (GU)"),
                    ("HI", "Hawaii (HI)"),
                    ("ID", "Idaho (ID)"),
                    ("IL", "Illinois (IL)"),
                    ("IN", "Indiana (IN)"),
                    ("IA", "Iowa (IA)"),
                    ("KS", "Kansas (KS)"),
                    ("KY", "Kentucky (KY)"),
                    ("LA", "Louisiana (LA)"),
                    ("ME", "Maine (ME)"),
                    ("MD", "Maryland (MD)"),
                    ("MA", "Massachusetts (MA)"),
                    ("MI", "Michigan (MI)"),
                    ("MN", "Minnesota (MN)"),
                    ("MS", "Mississippi (MS)"),
                    ("MO", "Missouri (MO)"),
                    ("MT", "Montana (MT)"),
                    ("NE", "Nebraska (NE)"),
                    ("NV", "Nevada (NV)"),
                    ("NH", "New Hampshire (NH)"),
                    ("NJ", "New Jersey (NJ)"),
                    ("NM", "New Mexico (NM)"),
                    ("NY", "New York (NY)"),
                    ("NC", "North Carolina (NC)"),
                    ("ND", "North Dakota (ND)"),
                    ("MP", "Northern Mariana Islands (MP)"),
                    ("OH", "Ohio (OH)"),
                    ("OK", "Oklahoma (OK)"),
                    ("OR", "Oregon (OR)"),
                    ("PA", "Pennsylvania (PA)"),
                    ("PR", "Puerto Rico (PR)"),
                    ("RI", "Rhode Island (RI)"),
                    ("SC", "South Carolina (SC)"),
                    ("SD", "South Dakota (SD)"),
                    ("TN", "Tennessee (TN)"),
                    ("TX", "Texas (TX)"),
                    ("UM", "United States Minor Outlying Islands (UM)"),
                    ("UT", "Utah (UT)"),
                    ("VT", "Vermont (VT)"),
                    ("VI", "Virgin Islands (VI)"),
                    ("VA", "Virginia (VA)"),
                    ("WA", "Washington (WA)"),
                    ("WV", "West Virginia (WV)"),
                    ("WI", "Wisconsin (WI)"),
                    ("WY", "Wyoming (WY)"),
                    ("AA", "Armed Forces Americas (AA)"),
                    ("AE", "Armed Forces Africa, Canada, Europe, Middle East (AE)"),
                    ("AP", "Armed Forces Pacific (AP)"),
                ],
                help_text="State, territory, or military post",
                max_length=2,
                null=True,
                verbose_name="state / territory",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="urbanization",
            field=models.CharField(
                blank=True,
                help_text="Urbanization (required for Puerto Rico only)",
                null=True,
                verbose_name="urbanization",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="zipcode",
            field=models.CharField(
                blank=True, db_index=True, help_text="Zip code", max_length=10, null=True, verbose_name="zip code"
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="is_election_board",
            field=models.BooleanField(
                blank=True,
                help_text="Is your organization an election office?",
                null=True,
                verbose_name="election office",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="state_territory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama (AL)"),
                    ("AK", "Alaska (AK)"),
                    ("AS", "American Samoa (AS)"),
                    ("AZ", "Arizona (AZ)"),
                    ("AR", "Arkansas (AR)"),
                    ("CA", "California (CA)"),
                    ("CO", "Colorado (CO)"),
                    ("CT", "Connecticut (CT)"),
                    ("DE", "Delaware (DE)"),
                    ("DC", "District of Columbia (DC)"),
                    ("FL", "Florida (FL)"),
                    ("GA", "Georgia (GA)"),
                    ("GU", "Guam (GU)"),
                    ("HI", "Hawaii (HI)"),
                    ("ID", "Idaho (ID)"),
                    ("IL", "Illinois (IL)"),
                    ("IN", "Indiana (IN)"),
                    ("IA", "Iowa (IA)"),
                    ("KS", "Kansas (KS)"),
                    ("KY", "Kentucky (KY)"),
                    ("LA", "Louisiana (LA)"),
                    ("ME", "Maine (ME)"),
                    ("MD", "Maryland (MD)"),
                    ("MA", "Massachusetts (MA)"),
                    ("MI", "Michigan (MI)"),
                    ("MN", "Minnesota (MN)"),
                    ("MS", "Mississippi (MS)"),
                    ("MO", "Missouri (MO)"),
                    ("MT", "Montana (MT)"),
                    ("NE", "Nebraska (NE)"),
                    ("NV", "Nevada (NV)"),
                    ("NH", "New Hampshire (NH)"),
                    ("NJ", "New Jersey (NJ)"),
                    ("NM", "New Mexico (NM)"),
                    ("NY", "New York (NY)"),
                    ("NC", "North Carolina (NC)"),
                    ("ND", "North Dakota (ND)"),
                    ("MP", "Northern Mariana Islands (MP)"),
                    ("OH", "Ohio (OH)"),
                    ("OK", "Oklahoma (OK)"),
                    ("OR", "Oregon (OR)"),
                    ("PA", "Pennsylvania (PA)"),
                    ("PR", "Puerto Rico (PR)"),
                    ("RI", "Rhode Island (RI)"),
                    ("SC", "South Carolina (SC)"),
                    ("SD", "South Dakota (SD)"),
                    ("TN", "Tennessee (TN)"),
                    ("TX", "Texas (TX)"),
                    ("UM", "United States Minor Outlying Islands (UM)"),
                    ("UT", "Utah (UT)"),
                    ("VT", "Vermont (VT)"),
                    ("VI", "Virgin Islands (VI)"),
                    ("VA", "Virginia (VA)"),
                    ("WA", "Washington (WA)"),
                    ("WV", "West Virginia (WV)"),
                    ("WI", "Wisconsin (WI)"),
                    ("WY", "Wyoming (WY)"),
                    ("AA", "Armed Forces Americas (AA)"),
                    ("AE", "Armed Forces Africa, Canada, Europe, Middle East (AE)"),
                    ("AP", "Armed Forces Pacific (AP)"),
                ],
                help_text="State, territory, or military post",
                max_length=2,
                null=True,
                verbose_name="state / territory",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="submission_date",
            field=models.DateField(
                blank=True, default=None, help_text="Date submitted", null=True, verbose_name="submitted at"
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="zipcode",
            field=models.CharField(
                blank=True, db_index=True, help_text="Zip code", max_length=10, null=True, verbose_name="zip code"
            ),
        ),
        migrations.AlterField(
            model_name="draftdomain",
            name="name",
            field=models.CharField(
                default=None, help_text="Fully qualified domain name", max_length=253, verbose_name="requested domain"
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(
                default=None, help_text="Fully qualified domain name", max_length=253, verbose_name="host name"
            ),
        ),
        migrations.AlterField(
            model_name="hostip",
            name="address",
            field=models.CharField(
                default=None,
                help_text="IP address",
                max_length=46,
                validators=[django.core.validators.validate_ipv46_address],
                verbose_name="IP address",
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="domain_name",
            field=models.CharField(blank=True, null=True, verbose_name="domain"),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="first_name",
            field=models.CharField(
                blank=True, db_index=True, help_text="First name / given name", null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="processed",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this TransitionDomain was already processed",
                verbose_name="processed",
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="state_territory",
            field=models.CharField(
                blank=True,
                help_text="State, territory, or military post",
                max_length=2,
                null=True,
                verbose_name="state / territory",
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("ready", "Ready"), ("on hold", "On hold"), ("unknown", "Unknown")],
                default="ready",
                help_text="domain status during the transfer",
                max_length=255,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="title",
            field=models.CharField(blank=True, help_text="Title", null=True, verbose_name="title / role"),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="username",
            field=models.CharField(help_text="Username - this will be an email address", verbose_name="username"),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="zipcode",
            field=models.CharField(
                blank=True, db_index=True, help_text="Zip code", max_length=10, null=True, verbose_name="zip code"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("restricted", "restricted")],
                default=None,
                max_length=10,
                null=True,
                verbose_name="user status",
            ),
        ),
    ]
