# Generated by Django 4.2.10 on 2024-04-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0085_alter_contact_first_name_alter_contact_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="updated_federal_agency",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated federal agency",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="registrar.federalagency",
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="updated_federal_agency",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated federal agency",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="registrar.federalagency",
            ),
        ),
    ]
