# Generated by Django 4.2.10 on 2024-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0085_domaininformation_cisa_representative_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrequest",
            name="has_anything_else_text",
            field=models.BooleanField(
                blank=True, help_text="Determines if the user has a anything_else or not", null=True
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="has_cisa_representative",
            field=models.BooleanField(
                blank=True, help_text="Determines if the user has a representative email or not", null=True
            ),
        ),
    ]
