# Generated by Django 4.2.10 on 2024-04-15 19:26

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0085_alter_domain_deleted_alter_domain_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("unknown", "Unknown"),
                    ("dns needed", "Dns needed"),
                    ("ready", "Ready"),
                    ("on hold", "On hold"),
                    ("deleted", "Deleted"),
                ],
                default="unknown",
                help_text=" ",
                max_length=21,
                protected=True,
            ),
        ),
    ]
