# Generated by Django 4.2.10 on 2024-04-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0087_alter_domain_deleted_alter_domain_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="cisa_representative_email",
            field=models.EmailField(blank=True, max_length=320, null=True, verbose_name="CISA regional representative"),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="cisa_representative_email",
            field=models.EmailField(blank=True, max_length=320, null=True, verbose_name="CISA regional representative"),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="has_anything_else_text",
            field=models.BooleanField(
                blank=True, help_text="Determines if the user has a anything_else or not", null=True
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="has_cisa_representative",
            field=models.BooleanField(
                blank=True, help_text="Determines if the user has a representative email or not", null=True
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="anything_else",
            field=models.TextField(blank=True, null=True, verbose_name="Additional details"),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="anything_else",
            field=models.TextField(blank=True, null=True, verbose_name="Additional details"),
        ),
    ]
