# Generated by Django 4.2.10 on 2024-04-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0088_domaininformation_cisa_representative_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domaininformation",
            name="federal_agency",
        ),
        migrations.RemoveField(
            model_name="domainrequest",
            name="federal_agency",
        ),
    ]
