# Generated by Django 4.2.10 on 2024-04-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0089_remove_domaininformation_federal_agency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domaininformation",
            old_name="updated_federal_agency",
            new_name="federal_agency",
        ),
        migrations.RenameField(
            model_name="domainrequest",
            old_name="updated_federal_agency",
            new_name="federal_agency",
        ),
    ]
