# Generated by Django 4.2.10 on 2024-05-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0089_user_verification_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publiccontact",
            unique_together={("contact_type", "registry_id", "domain")},
        ),
    ]
