# Generated by Django 4.2.10 on 2024-05-02 15:27

from django.db import migrations, models
import registrar.models.public_contact


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0089_user_verification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publiccontact",
            name="registry_id",
            field=models.CharField(
                default=registrar.models.public_contact.get_id,
                help_text="Auto generated ID to track this contact in the registry",
                max_length=16,
                unique=True,
            ),
        ),
    ]
