# Generated by Django 4.2.10 on 2024-05-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0090_waffleflag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publiccontact",
            unique_together={("contact_type", "registry_id", "domain")},
        ),
    ]
