# Generated by Django 4.2.10 on 2024-05-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0092_rename_updated_federal_agency_domaininformation_federal_agency_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publiccontact",
            unique_together={("contact_type", "registry_id", "domain")},
        ),
    ]
