# Generated by Django 4.2.10 on 2024-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0093_alter_publiccontact_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="finished_setup",
            field=models.BooleanField(default=True),
        ),
    ]
