# Generated by Django 4.2.10 on 2024-05-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0093_alter_contact_email_alter_contact_first_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publiccontact",
            unique_together={("contact_type", "registry_id", "domain")},
        ),
    ]
