# Generated by Django 4.2.10 on 2024-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0094_create_groups_v12"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, null=True, verbose_name="title / role"),
        ),
    ]
