# Generated by Django 4.2.10 on 2024-05-24 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0095_user_middle_name_user_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaffleSwitch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="The human/computer readable name.", max_length=100, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, help_text="Is this switch active?", verbose_name="Active"),
                ),
                (
                    "note",
                    models.TextField(blank=True, help_text="Note where this Switch is used.", verbose_name="Note"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when this Switch was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when this Switch was last modified.",
                        verbose_name="Modified",
                    ),
                ),
            ],
            options={
                "verbose_name": "waffle switch",
                "verbose_name_plural": "Waffle switches",
            },
        ),
    ]
