# Generated by Django 4.2.10 on 2024-05-28 14:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0095_user_middle_name_user_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, null=True, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, null=True, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="organization_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="zip code"),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="organization_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="zip code"),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="First name / given name", null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="organization_name",
            field=models.CharField(blank=True, help_text="Organization name", null=True),
        ),
        migrations.AlterField(
            model_name="transitiondomain",
            name="zipcode",
            field=models.CharField(blank=True, help_text="Zip code", max_length=10, null=True, verbose_name="zip code"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, help_text="Phone", max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="verifiedbystaff",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["user"], name="registrar_c_user_id_4059c4_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="registrar_c_email_bde2de_idx"),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(fields=["name"], name="registrar_d_name_5b1956_idx"),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(fields=["state"], name="registrar_d_state_84c134_idx"),
        ),
        migrations.AddIndex(
            model_name="domaininformation",
            index=models.Index(fields=["domain"], name="registrar_d_domain__88838a_idx"),
        ),
        migrations.AddIndex(
            model_name="domaininformation",
            index=models.Index(fields=["domain_request"], name="registrar_d_domain__d1fba8_idx"),
        ),
        migrations.AddIndex(
            model_name="domaininvitation",
            index=models.Index(fields=["status"], name="registrar_d_status_e84571_idx"),
        ),
        migrations.AddIndex(
            model_name="domainrequest",
            index=models.Index(fields=["requested_domain"], name="registrar_d_request_6894eb_idx"),
        ),
        migrations.AddIndex(
            model_name="domainrequest",
            index=models.Index(fields=["approved_domain"], name="registrar_d_approve_ac4c46_idx"),
        ),
        migrations.AddIndex(
            model_name="domainrequest",
            index=models.Index(fields=["status"], name="registrar_d_status_a32b59_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="registrar_u_usernam_964b1b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="registrar_u_email_c8f2c4_idx"),
        ),
    ]
