# Generated by Django 4.2.10 on 2024-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0095_user_middle_name_user_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrequest",
            name="action_needed_reason",
            field=models.TextField(
                blank=True,
                choices=[
                    ("eligibility_unclear", "Unclear organization eligibility"),
                    ("questionable_authorizing_official", "Questionable authorizing official"),
                    ("ALREADY_HAS_DOMAINS", "Already has domains"),
                    ("bad_name", "Doesn’t meet naming requirements"),
                    ("other", "Other (no auto-email sent)"),
                ],
                null=True,
            ),
        ),
    ]
