# Generated by Django 4.2.10 on 2024-05-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0095_user_middle_name_user_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publiccontact",
            unique_together={("contact_type", "registry_id", "domain")},
        ),
    ]
