# Generated by Django 4.2.10 on 2024-06-07 15:27

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0097_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("in review", "In review"),
                    ("action needed", "Action needed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("ineligible", "Ineligible"),
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("started", "Started"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
