# Generated by Django 4.2.10 on 2024-06-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0099_federalagency_federal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="cisa_representative_first_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative first name"
            ),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="cisa_representative_last_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative last name"
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="cisa_representative_first_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative first name"
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="cisa_representative_last_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative last name"
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="cisa_representative_email",
            field=models.EmailField(
                blank=True, max_length=320, null=True, verbose_name="CISA regional representative email"
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="cisa_representative_email",
            field=models.EmailField(
                blank=True, max_length=320, null=True, verbose_name="CISA regional representative email"
            ),
        ),
    ]
