# Generated by Django 4.2.10 on 2024-06-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0100_domainrequest_action_needed_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="cisa_representative_first_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative first name"
            ),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="cisa_representative_last_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative last name"
            ),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="has_anything_else_text",
            field=models.BooleanField(
                blank=True, help_text="Determines if the user has a anything_else or not", null=True
            ),
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="has_cisa_representative",
            field=models.BooleanField(
                blank=True, help_text="Determines if the user has a representative email or not", null=True
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="cisa_representative_first_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative first name"
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="cisa_representative_last_name",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="CISA regional representative last name"
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="cisa_representative_email",
            field=models.EmailField(
                blank=True, max_length=320, null=True, verbose_name="CISA regional representative email"
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="cisa_representative_email",
            field=models.EmailField(
                blank=True, max_length=320, null=True, verbose_name="CISA regional representative email"
            ),
        ),
    ]
