# Generated by Django 4.2.10 on 2024-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0100_domainrequest_action_needed_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="dsdata_last_change",
            field=models.TextField(blank=True, help_text="Most recent time that ds data was updated", null=True),
        ),
    ]
