# Generated by Django 4.2.10 on 2024-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0101_domaininformation_cisa_representative_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="dsdata_last_change",
            field=models.TextField(blank=True, help_text="Record of the last change event for ds data", null=True),
        ),
    ]
