# Generated by Django 4.2.10 on 2024-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0102_domain_dsdata_last_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrequest",
            name="action_needed_reason_email",
            field=models.TextField(blank=True, null=True),
        ),
    ]
