# Generated by Django 4.2.10 on 2024-06-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0104_create_groups_v13"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suborganization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Suborganization", max_length=1000, unique=True)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="registrar.portfolio")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomainGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Domain group", unique=True)),
                ("domains", models.ManyToManyField(blank=True, to="registrar.domaininformation")),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="registrar.portfolio")),
            ],
            options={
                "unique_together": {("name", "portfolio")},
            },
        ),
    ]
