# Generated by Django 4.2.10 on 2024-06-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0106_create_groups_v14"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The suborganization that this domain is included under",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_sub_organization",
                to="registrar.suborganization",
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The suborganization that this domain request is included under",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_sub_organization",
                to="registrar.suborganization",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="Portfolio associated with this domain",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="Portfolio associated with this domain request",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="DomainRequest_portfolio",
                to="registrar.portfolio",
            ),
        ),
    ]
