# Generated by Django 4.2.10 on 2024-06-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0106_create_groups_v14"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrequest",
            name="action_needed_reason_email",
            field=models.TextField(blank=True, null=True),
        ),
    ]
