# Generated by Django 4.2.10 on 2024-06-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0107_domainrequest_action_needed_reason_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domaininformation",
            name="authorizing_official",
        ),
        migrations.RemoveField(
            model_name="domainrequest",
            name="authorizing_official",
        ),
        migrations.AddField(
            model_name="domaininformation",
            name="senior_official",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_senior_official",
                to="registrar.contact",
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="senior_official",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="senior_official",
                to="registrar.contact",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="action_needed_reason",
            field=models.TextField(
                blank=True,
                choices=[
                    ("eligibility_unclear", "Unclear organization eligibility"),
                    ("questionable_senior_official", "Questionable senior official"),
                    ("already_has_domains", "Already has domains"),
                    ("bad_name", "Doesn’t meet naming requirements"),
                    ("other", "Other (no auto-email sent)"),
                ],
                null=True,
            ),
        ),
    ]
