# Generated by Django 4.2.10 on 2024-07-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0108_domaininformation_authorizing_official_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaininformation",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The suborganization that this domain is included under",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_sub_organization",
                to="registrar.suborganization",
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The suborganization that this domain request is included under",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_sub_organization",
                to="registrar.suborganization",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="Portfolio associated with this domain",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="approved_domain",
            field=models.OneToOneField(
                blank=True,
                help_text="Domain associated with this request; will be blank until request is approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_request_approved_domain",
                to="registrar.domain",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="Portfolio associated with this domain request",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="DomainRequest_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="requested_domain",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domain_request_requested_domain",
                to="registrar.draftdomain",
            ),
        ),
    ]
