# Generated by Django 4.2.10 on 2024-07-02 21:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0109_domaininformation_sub_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeniorOfficial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(verbose_name="first name")),
                ("last_name", models.CharField(verbose_name="last name")),
                ("title", models.CharField(verbose_name="title / role")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
                ),
                ("email", models.EmailField(blank=True, max_length=320, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="portfolio",
            name="senior_official",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated senior official",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="registrar.seniorofficial",
            ),
        ),
    ]
