# Generated by Django 4.2.10 on 2024-08-01 12:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0114_alter_user_portfolio_additional_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "portfolio_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("organization_admin", "Admin"),
                                ("organization_admin_read_only", "Admin read only"),
                                ("organization_member", "Member"),
                            ],
                            max_length=50,
                        ),
                        blank=True,
                        help_text="Select one or more roles.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "portfolio_additional_permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("view_all_domains", "View all domains and domain reports"),
                                ("view_managed_domains", "View managed domains"),
                                ("view_member", "View members"),
                                ("edit_member", "Create and edit members"),
                                ("view_all_requests", "View all requests"),
                                ("view_created_requests", "View created requests"),
                                ("edit_requests", "Create and edit requests"),
                                ("view_portfolio", "View organization"),
                                ("edit_portfolio", "Edit organization"),
                            ],
                            max_length=50,
                        ),
                        blank=True,
                        help_text="Select one or more additional permissions.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[("invited", "Invited"), ("retrieved", "Retrieved")],
                        default="invited",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="portfolios", to="registrar.portfolio"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status"], name="registrar_p_status_aa4218_idx")],
            },
        ),
    ]
