# Generated by Django 4.2.10 on 2024-08-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0115_portfolioinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="federalagency",
            name="initials",
            field=models.CharField(blank=True, help_text="Agency initials", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="federalagency",
            name="is_fceb",
            field=models.BooleanField(
                blank=True, help_text="Determines if this agency is FCEB", null=True, verbose_name="FCEB"
            ),
        ),
        migrations.AddField(
            model_name="seniorofficial",
            name="federal_agency",
            field=models.ForeignKey(
                blank=True,
                help_text="The federal agency this user is associated with",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="so_federal_agency",
                to="registrar.federalagency",
            ),
        ),
        migrations.AlterField(
            model_name="seniorofficial",
            name="first_name",
            field=models.CharField(blank=True, null=True, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="seniorofficial",
            name="last_name",
            field=models.CharField(blank=True, null=True, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="seniorofficial",
            name="title",
            field=models.CharField(blank=True, null=True, verbose_name="title / role"),
        ),
    ]
