# Generated by Django 4.2.10 on 2024-08-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0117_alter_portfolioinvitation_portfolio_additional_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="federal_type",
            field=models.CharField(
                blank=True,
                choices=[("executive", "Executive"), ("judicial", "Judicial"), ("legislative", "Legislative")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="suborganization",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portfolio_suborganizations",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_users",
                to="registrar.portfolio",
            ),
        ),
    ]
