# Generated by Django 4.2.10 on 2024-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0119_remove_user_portfolio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domainrequest",
            old_name="submission_date",
            new_name="last_submitted_date",
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="last_submitted_date",
            field=models.DateField(
                blank=True, default=None, help_text="Date last submitted", null=True, verbose_name="last submitted on"
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="first_submitted_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Date initially submitted",
                null=True,
                verbose_name="first submitted on",
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="last_status_update",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Date of the last status update",
                null=True,
                verbose_name="last updated on",
            ),
        ),
    ]
