# Generated by Django 4.2.10 on 2024-08-29 24:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0125_delete_cascade_submitter_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domaininformation",
            name="submitter",
        ),
        migrations.RemoveField(
            model_name="domainrequest",
            name="submitter",
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="creator",
            field=models.ForeignKey(
                help_text="Person who submitted the domain request. Will receive email updates.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domain_requests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
