# Generated by Django 4.2.10 on 2024-09-25 00:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0128_alter_domaininformation_state_territory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioinvitation",
            name="portfolio_roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("organization_admin", "Admin"), ("organization_member", "Member")], max_length=50
                ),
                blank=True,
                help_text="Select one or more roles.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userportfoliopermission",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("organization_admin", "Admin"), ("organization_member", "Member")], max_length=50
                ),
                blank=True,
                help_text="Select one or more roles.",
                null=True,
                size=None,
            ),
        ),
    ]
