# Generated by Django 4.2.10 on 2024-09-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0128_alter_domaininformation_state_territory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrequest",
            name="rejection_reason_email",
            field=models.TextField(blank=True, null=True),
        ),
    ]
