# Generated by Django 4.2.10 on 2024-09-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0129_create_groups_v17"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="organization_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
