# Generated by Django 4.2.10 on 2024-09-30 17:59

from django.db import migrations, models
import django.db.models.deletion
import registrar.models.federal_agency


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0129_alter_portfolioinvitation_portfolio_roles_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="federalagency",
            old_name="initials",
            new_name="acronym",
        ),
        migrations.AlterField(
            model_name="federalagency",
            name="acronym",
            field=models.CharField(
                blank=True,
                help_text="Acronym commonly used to reference the federal agency (Optional)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, domain is not associated with a portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, domain is associated with the overarching organization for this portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_sub_organization",
                to="registrar.suborganization",
                verbose_name="Suborganization",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, request is not associated with a portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="DomainRequest_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, request is associated with the overarching organization for this portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_sub_organization",
                to="registrar.suborganization",
                verbose_name="Suborganization",
            ),
        ),
        migrations.AlterField(
            model_name="federalagency",
            name="federal_type",
            field=models.CharField(
                blank=True,
                choices=[("executive", "Executive"), ("judicial", "Judicial"), ("legislative", "Legislative")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="federalagency",
            name="is_fceb",
            field=models.BooleanField(
                blank=True, help_text="Federal Civilian Executive Branch (FCEB)", null=True, verbose_name="FCEB"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="federal_agency",
            field=models.ForeignKey(
                default=registrar.models.federal_agency.FederalAgency.get_non_federal_agency,
                on_delete=django.db.models.deletion.PROTECT,
                to="registrar.federalagency",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="organization_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federal", "Federal"),
                    ("interstate", "Interstate"),
                    ("state_or_territory", "State or territory"),
                    ("tribal", "Tribal"),
                    ("county", "County"),
                    ("city", "City"),
                    ("special_district", "Special district"),
                    ("school_district", "School district"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="senior_official",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portfolios",
                to="registrar.seniorofficial",
            ),
        ),
        migrations.AlterField(
            model_name="suborganization",
            name="name",
            field=models.CharField(max_length=1000, unique=True, verbose_name="Suborganization"),
        ),
    ]
