# Generated by Django 4.2.10 on 2024-09-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0130_remove_federalagency_initials_federalagency_acronym_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaininformation",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, domain is not associated with a portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, domain is associated with the overarching organization for this portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_sub_organization",
                to="registrar.suborganization",
                verbose_name="Suborganization",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, request is not associated with a portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="DomainRequest_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, request is associated with the overarching organization for this portfolio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_sub_organization",
                to="registrar.suborganization",
                verbose_name="Suborganization",
            ),
        ),
    ]
