# Generated by Django 4.2.10 on 2024-10-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0131_create_groups_v17"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaininformation",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="information_portfolio",
                to="registrar.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="DomainRequest_portfolio",
                to="registrar.portfolio",
            ),
        ),
    ]
