# Generated by Django 4.2.10 on 2024-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrar",
            "0134_rename_portfolio_additional_permissions_portfolioinvitation_additional_permissions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="federalagency",
            name="agency",
            field=models.CharField(null=True, verbose_name="Federal agency"),
        ),
        migrations.AlterField(
            model_name="federalagency",
            name="federal_type",
            field=models.CharField(
                choices=[("executive", "Executive"), ("judicial", "Judicial"), ("legislative", "Legislative")],
                max_length=20,
                null=True,
            ),
        ),
    ]
