# Generated by Django 4.2.10 on 2024-11-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0136_domaininformation_requested_suborganization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domaininformation",
            name="requested_suborganization",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="suborganization_city",
        ),
        migrations.RemoveField(
            model_name="domaininformation",
            name="suborganization_state_territory",
        ),
    ]
