# Generated by Django 4.2.10 on 2024-11-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0137_alter_domaininvitation_status"),
        ("registrar", "0137_suborganization_city_suborganization_state_territory"),
    ]

    operations = []
