# Generated by Django 4.2.10 on 2024-11-18 16:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0137_suborganization_city_suborganization_state_territory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaininvitation",
            name="status",
            field=django_fsm.FSMField(
                choices=[("invited", "Invited"), ("retrieved", "Retrieved"), ("canceled", "Canceled")],
                default="invited",
                max_length=50,
                protected=True,
            ),
        ),
    ]
