# Generated by Django 4.2.10 on 2024-11-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0137_suborganization_city_suborganization_state_territory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userportfoliopermission",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_user_portfolio_permission",
                to="registrar.portfolioinvitation",
            ),
        ),
    ]
