# Generated by Django 4.2.10 on 2024-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0138_alter_domaininvitation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainrequest",
            name="action_needed_reason",
            field=models.TextField(
                blank=True,
                choices=[
                    ("eligibility_unclear", "Unclear organization eligibility"),
                    ("questionable_senior_official", "Questionable senior official"),
                    ("already_has_a_domain", "Already has a domain"),
                    ("bad_name", "Doesn’t meet naming requirements"),
                    ("other", "Other (no auto-email sent)"),
                ],
                null=True,
            ),
        ),
    ]
