# Generated by Django 4.2.10 on 2024-12-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0139_alter_domainrequest_action_needed_reason"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="suborganization",
            unique_together={("name", "portfolio")},
        ),
    ]
