# Generated by Django 4.2.17 on 2025-02-28 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0140_alter_portfolioinvitation_additional_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioinvitation",
            name="additional_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("view_all_domains", "Viewer"),
                        ("view_managed_domains", "Viewer, limited (domains they manage)"),
                        ("view_members", "Viewer"),
                        ("edit_members", "Manager"),
                        ("view_all_requests", "Viewer"),
                        ("edit_requests", "Creator"),
                        ("view_portfolio", "Viewer"),
                        ("edit_portfolio", "Manager"),
                    ],
                    max_length=50,
                ),
                blank=True,
                help_text="Select one or more additional permissions.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioinvitation",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("organization_admin", "Admin"), ("organization_member", "Basic")], max_length=50
                ),
                blank=True,
                help_text="Select one or more roles.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userportfoliopermission",
            name="additional_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("view_all_domains", "Viewer"),
                        ("view_managed_domains", "Viewer, limited (domains they manage)"),
                        ("view_members", "Viewer"),
                        ("edit_members", "Manager"),
                        ("view_all_requests", "Viewer"),
                        ("edit_requests", "Creator"),
                        ("view_portfolio", "Viewer"),
                        ("edit_portfolio", "Manager"),
                    ],
                    max_length=50,
                ),
                blank=True,
                help_text="Select one or more additional permissions.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userportfoliopermission",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("organization_admin", "Admin"), ("organization_member", "Basic")], max_length=50
                ),
                blank=True,
                help_text="Select one or more roles.",
                null=True,
                size=None,
            ),
        ),
    ]
