# Generated by Django 4.2.17 on 2025-02-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0140_alter_portfolioinvitation_additional_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrequest",
            name="feb_naming_requirements",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="feb_naming_requirements_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
