# Generated by Django 4.2.17 on 2025-02-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0141_domainrequest_feb_naming_requirements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrequest",
            name="feb_purpose_choice",
            field=models.CharField(
                blank=True, choices=[("website", "Website"), ("redirect", "Redirect"), ("other", "Other")], null=True
            ),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="has_timeframe",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="interagency_initiative_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="is_interagency_initiative",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domainrequest",
            name="time_frame_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
