# Generated by Django 4.2.20 on 2025-04-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0146_remove_domainrequest_eop_stakeholder_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hostip",
            options={"verbose_name": "Host IP", "verbose_name_plural": "Host IPs"},
        ),
    ]
