# Generated by Django 4.2.20 on 2025-05-14 16:40

from django.db import migrations, models
import registrar.models.utility.domain_field


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0147_alter_hostip_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=registrar.models.utility.domain_field.DomainField(
                default=None, help_text="Fully qualified domain name", max_length=253, verbose_name="domain"
            ),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "deleted"), _negated=True),
                fields=("name",),
                name="unique_name_except_deleted",
            ),
        ),
    ]
