# Generated by Django 4.2.20 on 2025-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0148_alter_domain_name_domain_unique_name_except_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainrequest",
            name="feb_purpose_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "Used for a new website"),
                    ("redirect", "Used as a redirect for an existing or new website"),
                    ("other", "Not for a website"),
                ],
                null=True,
                verbose_name="Purpose type",
            ),
        ),
    ]
