# Generated by Django 4.2.20 on 2025-05-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0149_alter_domainrequest_feb_purpose_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainrequest",
            name="eop_stakeholder_first_name",
        ),
        migrations.RemoveField(
            model_name="domainrequest",
            name="eop_stakeholder_last_name",
        ),
        migrations.RemoveField(
            model_name="domainrequest",
            name="working_with_eop",
        ),
    ]
