# Generated by Django 4.2.20 on 2025-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0150_remove_domainrequest_eop_stakeholder_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suborganization",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Suborganization"),
        ),
    ]
