# Generated by Django 4.2.20 on 2025-06-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0150_remove_domainrequest_eop_stakeholder_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="organization_name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="suborganization",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Suborganization"),
        ),
        migrations.AddConstraint(
            model_name="suborganization",
            constraint=models.UniqueConstraint(fields=("portfolio", "name"), name="unique_portfolio_name"),
        ),
    ]
