# Generated by Django 4.2.20 on 2025-06-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0150_remove_domainrequest_eop_stakeholder_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suborganization",
            options={"ordering": ["name"]},
        ),
    ]
