# Generated by Django 4.2.20 on 2025-06-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0151_alter_suborganization_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE registrar_suborganization DROP CONSTRAINT " "registrar_suborganization_name_key"
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="organization_name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="suborganization",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Suborganization"),
        ),
        migrations.AddConstraint(
            model_name="suborganization",
            constraint=models.UniqueConstraint(fields=("name", "portfolio"), name="unique_name_portfolio"),
        ),
    ]
