# Generated by Django 4.2.20 on 2025-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0151_alter_suborganization_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="organization_name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="suborganization",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Suborganization"),
        ),
    ]
