# Generated by Django 4.2.20 on 2025-07-15 04:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0152_alter_portfolio_organization_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioinvitation",
            name="additional_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("view_all_domains", "Viewer"),
                        ("view_managed_domains", "Viewer, limited (domains they manage)"),
                        ("view_members", "Viewer"),
                        ("edit_members", "Manager"),
                        ("view_all_requests", "Viewer"),
                        ("edit_requests", "Requester"),
                        ("view_portfolio", "Viewer"),
                        ("edit_portfolio", "Manager"),
                    ],
                    max_length=50,
                ),
                blank=True,
                help_text="Select one or more additional permissions.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userportfoliopermission",
            name="additional_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("view_all_domains", "Viewer"),
                        ("view_managed_domains", "Viewer, limited (domains they manage)"),
                        ("view_members", "Viewer"),
                        ("edit_members", "Manager"),
                        ("view_all_requests", "Viewer"),
                        ("edit_requests", "Requester"),
                        ("view_portfolio", "Viewer"),
                        ("edit_portfolio", "Manager"),
                    ],
                    max_length=50,
                ),
                blank=True,
                help_text="Select one or more additional permissions.",
                null=True,
                size=None,
            ),
        ),
    ]
