# Generated by Django 4.2.20 on 2025-08-12 14:21

from django.db import migrations, models


def remove_old_flags(apps, schema_editor):
    """
    Forward migration to delete the specified WaffleFlag objects
    """

    WaffleFlag = apps.get_model("registrar", "WaffleFlag")

    flags_to_remove = ["organization_feature", "organization_members", "organization_requests"]

    for flag_name in flags_to_remove:
        try:
            WaffleFlag.objects.get(name=flag_name).delete()
        except WaffleFlag.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0153_alter_portfolioinvitation_additional_permissions_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_old_flags,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
    ]
