# Generated by Django 4.2.20 on 2025-09-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0154_remove_waffle_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federalagency",
            name="federal_type",
            field=models.CharField(
                blank=True,
                choices=[("executive", "Executive"), ("judicial", "Judicial"), ("legislative", "Legislative")],
                max_length=20,
                null=True,
            ),
        ),
    ]
