# Generated by Django 4.2.20 on 2025-09-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0154_remove_waffle_flags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domaininformation",
            old_name="creator",
            new_name="requester",
        ),
        migrations.RenameField(
            model_name="domainrequest",
            old_name="creator",
            new_name="requester",
        ),
        migrations.RenameField(
            model_name="portfolio",
            old_name="creator",
            new_name="requester",
        ),
    ]
