# Generated by Django 4.2.20 on 2025-09-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0155_rename_creator_domaininformation_requester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaininformation",
            name="no_other_contacts_rationale",
            field=models.TextField(
                blank=True, help_text="Required if requester does not list other employees", null=True
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="alternative_domains",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other domain names the requester provided for consideration",
                related_name="alternatives+",
                to="registrar.website",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="no_other_contacts_rationale",
            field=models.TextField(
                blank=True, help_text="Required if requester does not list other employees", null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_portfolios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Portfolio requester",
            ),
        ),
    ]
