# Generated by Django 4.2.20 on 2025-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0155_alter_federalagency_federal_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domaininformation",
            old_name="creator",
            new_name="requester",
        ),
        migrations.RenameField(
            model_name="domainrequest",
            old_name="creator",
            new_name="requester",
        ),
        migrations.RenameField(
            model_name="portfolio",
            old_name="creator",
            new_name="requester",
        ),
        migrations.AlterField(
            model_name="domaininformation",
            name="no_other_contacts_rationale",
            field=models.TextField(
                blank=True, help_text="Required if requester does not list other employees", null=True
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="alternative_domains",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other domain names the requester provided for consideration",
                related_name="alternatives+",
                to="registrar.website",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="no_other_contacts_rationale",
            field=models.TextField(
                blank=True, help_text="Required if requester does not list other employees", null=True
            ),
        ),
    ]
