# Generated by Django 4.2.20 on 2025-09-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0155_alter_federalagency_federal_type"),
        ("registrar", "0156_alter_domaininformation_no_other_contacts_rationale_and_more"),
    ]

    operations = []
