# Generated by Django 4.2.20 on 2025-10-03 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0156_rename_creator_domaininformation_requester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_portfolios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Portfolio requester",
            ),
        ),
    ]
