# Generated by Django 4.2.20 on 2025-10-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0157_alter_portfolio_requester"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="agency_seal",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
