# Generated by Django 4.2.20 on 2025-10-15 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0158_dnsaccount_dnsrecord_dnsvendor_dnszone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainrequest",
            name="investigator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_requests_investigating",
                to=settings.AUTH_USER_MODEL,
                verbose_name="analyst",
            ),
        ),
    ]
