# Generated by Django 4.2.20 on 2025-10-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0159_alter_domainrequest_investigator"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="agency_seal",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
