# Generated by Django 4.2.20 on 2025-10-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0160_portfolio_agency_seal"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsaccount_vendordnsaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="dnsaccount_vendordnsaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("dns_account",),
                name="unique_active_vendor_account_per_dns_account",
            ),
        ),
    ]
