# Generated by Django 4.2.20 on 2025-10-20 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0160_portfolio_agency_seal"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomainrole",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdomainrole",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userdomainrole",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdomainrole",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_roles_invited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdomainrole",
            name="revocation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdomainrole",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdomainrole",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                help_text="Status of the invitation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userportfoliopermission",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userportfoliopermission",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userportfoliopermission",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userportfoliopermission",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_portfolio_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userportfoliopermission",
            name="revocation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userportfoliopermission",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userportfoliopermission",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                help_text="Status of the portfolio permission invitation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userdomainrole",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userportfoliopermission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
