# Generated by Django 4.2.20 on 2025-10-29 14:40

from django.db import migrations


def populate_cloudflare_vendor(apps, schema_editor):
    CF = "cloudflare"
    DnsVendor = apps.get_model("registrar", "DnsVendor")
    DnsVendor.objects.create(name=CF)

def unpopulate_cloudflare_vendor(apps, schema_editor):
    DnsVendor = apps.get_model("registrar", "DnsVendor")
    DnsVendor.objects.filter(name="cloudflare").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0163_userdomainrole_accepted_at_userdomainrole_email_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_cloudflare_vendor, unpopulate_cloudflare_vendor),
    ]
