# Generated by Django 4.2.20 on 2025-10-29 14:40

from django.db import migrations
from registrar.models.dns.dns_vendor import DnsVendor


def seed_cloudflare_vendor(apps, schema_editor):
    CF = "cloudflare"
    DnsVendor.objects.get_or_create(name=CF)


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0163_userdomainrole_accepted_at_userdomainrole_email_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_cloudflare_vendor),
    ]
