# Generated by Django 4.2.20 on 2025-10-27 21:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0163_userdomainrole_accepted_at_userdomainrole_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("in review", "In review"),
                    ("in review - omb", "In review - OMB"),
                    ("action needed", "Action needed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("ineligible", "Ineligible"),
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("started", "Started"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
