# Generated by Django 4.2.20 on 2025-10-30 16:48

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import registrar.models.dns.dns_record


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0164_alter_domain_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsrecord",
            name="comment",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dnsrecord",
            name="content",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dnsrecord",
            name="priority",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dnsrecord",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="dnsrecord",
            name="ttl",
            field=models.PositiveIntegerField(
                default=1, validators=[registrar.models.dns.dns_record.DnsRecord.validate_ttl]
            ),
        ),
        migrations.AddField(
            model_name="dnsrecord",
            name="type",
            field=models.CharField(choices=[("a", "A")], default="a"),
        ),
        migrations.AddField(
            model_name="dnsrecord_vendordnsrecord",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="dnsrecord_vendordnsrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("dns_record",),
                name="unique_active_vendor_record_per_dns_record",
            ),
        ),
    ]
