# Generated by Django 4.2.26 on 2025-12-15 21:46
# To update DnsZone's primary key from domain to id, we're deleting then recreating DnsZone.
# Remove foreign keys related to DnsZone.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0166_dnsrecord_comment_dnsrecord_content_dnsrecord_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dnszone_vendordnszone",
            name="unique_active_vendor_zone_per_dns_zone",
        ),
        migrations.RemoveField(
            model_name="dnsrecord",
            name="dns_zone",
        ),
        migrations.RemoveField(
            model_name="dnszone",
            name="vendor_dns_zone",
        ),
        migrations.RemoveField(
            model_name="dnszone_vendordnszone",
            name="dns_zone",
        ),
    ]
