# Generated by Django 4.2.26 on 2025-12-15 21:54
# To update DnsZone's primary key from domain to id, we're deleting then recreating DnsZone.
# Delete DnsZone model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0167_remove_dnszone_vendordnszone_unique_active_vendor_zone_per_dns_zone_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DnsZone",
        ),
    ]
