# Generated by Django 4.2.26 on 2025-12-15 21:58
# To update DnsZone's primary key from domain to id, we're deleting then recreating DnsZone.
# Create new DnsZone model with primary key id.

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import registrar.models.dns.dns_soa


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0168_delete_dnszone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, null=True)),
                (
                    "nameservers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                ("flatten_all_cnames", models.BooleanField(default=False)),
                ("foundation_dns", models.BooleanField(default=False)),
                ("multiprovider", models.BooleanField(default=False)),
                ("ns_ttl", models.PositiveIntegerField(default=86400)),
                ("secondary_overrides", models.BooleanField(default=False)),
                (
                    "zone_mode",
                    models.CharField(
                        choices=[("standard", "Standard"), ("cdn_only", "CDN Only"), ("dns_only", "DNS Only")],
                        default="standard",
                    ),
                ),
                (
                    "dns_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="zones", to="registrar.dnsaccount"
                    ),
                ),
                ("domain", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="registrar.domain")),
                (
                    "soa",
                    models.ForeignKey(
                        default=registrar.models.dns.dns_soa.DnsSoa.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="registrar.dnssoa",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
