# Generated by Django 4.2.26 on 2025-12-15 22:03
# To update DnsZone's primary key from domain to id, we're deleting then recreating DnsZone.
# Readd references to DnsZone in other models.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0169_dnszone"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsrecord",
            name="dns_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="records", to="registrar.dnszone"
            ),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="vendor_dns_zone",
            field=models.ManyToManyField(
                related_name="zones", through="registrar.DnsZone_VendorDnsZone", to="registrar.vendordnszone"
            ),
        ),
        migrations.AddField(
            model_name="dnszone_vendordnszone",
            name="dns_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="zone_link", to="registrar.dnszone"
            ),
        ),
        migrations.AddConstraint(
            model_name="dnszone_vendordnszone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("dns_zone",),
                name="unique_active_vendor_zone_per_dns_zone",
            ),
        ),
    ]
