# Generated by Django 4.2.26 on 2026-01-06 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0171_remove_waffle_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnszone",
            name="name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="dnszone",
            name="nameservers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=None, size=None
            ),
        ),
        migrations.AlterField(
            model_name="vendordnsaccount",
            name="x_account_id",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
