# Generated by Django 4.2.26 on 2026-02-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0172_alter_dnszone_name_alter_dnszone_nameservers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_enrolled_in_dns_hosting",
            field=models.BooleanField(
                default=False, help_text="Indicates whether this domain is enrolled in internal DNS hosting. "
            ),
        ),
    ]
