# Generated by Django 4.2.26 on 2026-02-04 22:05

from django.db import migrations, models
import registrar.validations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0172_alter_dnszone_name_alter_dnszone_nameservers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="comment",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(max_length=255, validators=[registrar.validations.validate_dns_name]),
        ),
        migrations.AlterField(
            model_name="dnsrecord",
            name="type",
            field=models.CharField(choices=[("a", "A")]),
        ),
    ]
