# Generated by Django 4.2.26 on 2026-02-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0173_domain_is_enrolled_in_dns_hosting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="is_enrolled_in_dns_hosting",
            field=models.BooleanField(
                default=False, help_text="Indicates whether this domain is enrolled in internal DNS hosting."
            ),
        ),
    ]
