# Generated by Django 4.2.26 on 2026-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0174_alter_dnsrecord_comment_alter_dnsrecord_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="created_at_reference",
            field=models.DateTimeField(
                blank=True, editable=False, help_text="Date the domain record was created in the registrar", null=True
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="registry_created_at",
            field=models.DateTimeField(
                blank=True, editable=False, help_text="Date the domain record was created in the registry", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("registry_created_at__isnull", True),
                    ("created_at_reference__lte", models.F("registry_created_at")),
                    _connector="OR",
                ),
                name="domain_created_at_reference_lte_registry_created_at",
            ),
        ),
    ]
