# Generated by Django 4.2.26 on 2026-02-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0174_alter_dnsrecord_comment_alter_dnsrecord_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="type",
            field=models.CharField(
                choices=[("A", "A"), ("AAAA", "AAAA"), ("CNAME", "CNAME"), ("MX", "MX"), ("PTR", "PTR"), ("TXT", "TXT")]
            ),
        ),
    ]
