# Generated by Django 4.2.26 on 2026-03-12 20:29

from django.db import migrations, models
import registrar.validations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0175_alter_dnsrecord_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="content",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(max_length=253, validators=[registrar.validations.validate_dns_name]),
        ),
        migrations.AlterField(
            model_name="dnszone",
            name="name",
            field=models.CharField(blank=True, max_length=253, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vendordnsrecord",
            name="x_record_id",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="vendordnszone",
            name="x_zone_id",
            field=models.CharField(max_length=32),
        ),
    ]
