# Generated by Django 4.2.26 on 2026-02-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0175_domain_created_at_reference_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="domain",
            name="domain_created_at_reference_lte_registry_created_at",
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("registry_created_at__isnull", True),
                    ("created_at", models.F("registry_created_at")),
                    _connector="OR",
                ),
                name="domain_created_at_reference_lte_registry_created_at",
            ),
        ),
    ]
