# Generated by Django 4.2.26

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0175_alter_dnsrecord_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsrecord",
            name="priority",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
    ]
