# Generated by Django 4.2.29 on 2026-04-24 13:17

from django.db import migrations, models
import registrar.validations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0177_dnsrecord_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(
                error_messages={
                    "max_length": "Labels must be no more than 63 characters. Full name (including labels, domain, and period) must be no more than 253 characters."
                },
                max_length=253,
                validators=[registrar.validations.validate_dns_name],
            ),
        ),
    ]
