# Generated by Django 4.2.29 on 2026-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0177_dnsrecord_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsOperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_email", models.CharField(blank=True, default="", max_length=255)),
                ("request_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create_dns_record", "Create DNS record"),
                            ("update_dns_record", "Update DNS record"),
                            ("enroll_domain", "Enroll domain in DNS hosting"),
                        ],
                        max_length=64,
                    ),
                ),
                ("outcome", models.CharField(choices=[("success", "Success"), ("failure", "Failure")], max_length=16)),
                ("domain_name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("dns_account_id", models.CharField(blank=True, default="", max_length=255)),
                ("zone_id", models.CharField(blank=True, default="", max_length=255)),
                ("record_id", models.CharField(blank=True, default="", max_length=255)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("upstream_status", models.IntegerField(blank=True, null=True)),
                ("cf_ray", models.CharField(blank=True, default="", max_length=255)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "DNS operation log entry",
                "verbose_name_plural": "DNS operation log",
                "ordering": ("-timestamp",),
            },
        ),
    ]
