# Generated by Django 4.2.29 on 2026-04-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0177_dnsrecord_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="content",
            field=models.CharField(blank=True, max_length=4080, null=True),
        ),
    ]
