# Generated by Django 4.2.29 on 2026-04-15 16:07

from django.db import migrations, models
import registrar.validations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0177_dnsrecord_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(max_length=255, validators=[registrar.validations.validate_dns_name]),
        ),
    ]
