# Generated by Django 4.2.29 on 2026-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0178_alter_dnsrecord_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsErrorMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "namespace",
                    models.CharField(
                        default="dns",
                        help_text="Future-proof grouping. v1 ships only the 'dns' namespace.",
                        max_length=32,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Matches DnsHostingErrorCodes member name, e.g. ZONE_NOT_FOUND.", max_length=64
                    ),
                ),
                ("message", models.TextField(help_text="What the user will see.")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Context for editors: where does this appear? What triggers it?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DNS error message",
                "verbose_name_plural": "DNS error messages",
                "ordering": ("namespace", "code"),
            },
        ),
        migrations.AddConstraint(
            model_name="dnserrormessage",
            constraint=models.UniqueConstraint(
                fields=("namespace", "code"), name="dns_error_message_unique_namespace_code"
            ),
        ),
    ]
