# Generated by Django 4.2.29 on 2026-05-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0178_alter_dnsrecord_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="created_at_reference",
            field=models.DateTimeField(
                blank=True, help_text="Date the domain record was created in the registrar", null=True
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="x_registry_created_at",
            field=models.DateTimeField(
                blank=True, help_text="Date the domain record was created in the registry", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.CheckConstraint(  # type: ignore[call-arg]
                check=models.Q(
                    ("x_registry_created_at__isnull", True),
                    ("created_at_reference__lte", models.F("x_registry_created_at")),
                    _connector="OR",
                ),
                name="domain_created_at_reference_lte_x_registry_created_at",
            ),
        ),
    ]
