# Generated by Django 4.2.29 on 2026-04-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0178_alter_dnsrecord_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userportfoliopermission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
