# Generated by Django 4.2.29 on 2026-05-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0178_alter_dnsrecord_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="content",
            field=models.CharField(blank=True, max_length=4080, null=True),
        ),
    ]
