# Generated by Django 5.2.12 on 2026-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0179_domain_created_at_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="domains",
            field=models.ManyToManyField(
                related_name="users",
                through="registrar.UserDomainRole",
                through_fields=("user", "domain"),
                to="registrar.domain",
            ),
        ),
    ]
