# Generated by Django 4.2.29 on 2026-05-18 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0179_domain_created_at_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userportfoliopermission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
