# Generated by Django 4.2.29 on 2026-05-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0180_alter_domaininformation_sub_organization_and_more"),
        ("registrar", "0181_alter_dnsrecord_content"),
    ]

    operations = []
