# Generated by Django 5.2.14 on 2026-05-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0182_alter_user_domains"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="domain",
            name="domain_created_at_reference_lte_x_registry_created_at",
        ),
    ]
