# Generated by Django 4.2.29 on 2026-05-29 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0182_alter_user_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomainrole",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
