# Generated by Django 5.2.14 on 2026-06-05 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0184_federaltribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaininformation",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, domain is associated with the overarching organization for this portfolio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="information_sub_organization",
                to="registrar.suborganization",
                verbose_name="Suborganization",
            ),
        ),
        migrations.AlterField(
            model_name="domainrequest",
            name="sub_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, request is associated with the overarching organization for this portfolio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_sub_organization",
                to="registrar.suborganization",
                verbose_name="Suborganization",
            ),
        ),
    ]
