# Generated by Django 5.2.14 on 2026-06-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0186_create_groups_v20"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomainrole",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
