# Generated by Django 5.2.14 on 2026-06-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0186_create_groups_v20"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="federaltribe",
            options={
                "ordering": ["tribe_full_name"],
                "verbose_name": "Federal tribe",
                "verbose_name_plural": "Federal tribes",
            },
        ),
    ]
