# Generated by Django 5.2.14 on 2026-07-02 23:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0190_create_groups_v21"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federaltribe",
            name="email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=320),
                blank=True,
                default=list,
                help_text="List of email addresses for the tribal leader or designated contact",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="statetribe",
            name="email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=320),
                blank=True,
                default=list,
                help_text="List of email addresses for the tribal leader or designated contact",
                null=True,
                size=None,
            ),
        ),
    ]
