# Generated by Django 5.2.16 on 2026-08-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0193_create_groups_v23"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="is_enrolled_in_dns_hosting",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the domain is enrolled in .gov DNS hosting.",
                verbose_name=".gov DNS",
            ),
        ),
    ]
