# Generated by Django 5.2.17 on 2026-08-27 16:56

import registrar.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0194_alter_domain_is_enrolled_in_dns_hosting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dnsrecord",
            options={"verbose_name": "DNS Record", "verbose_name_plural": "DNS Records"},
        ),
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(
                error_messages={
                    "max_length": "Labels must be no more than 63 characters. Full name (including labels, domain, and period) must be no more than 253 characters."
                },
                max_length=253,
                validators=[registrar.validations.validate_dns_name],
                verbose_name="Record name",
            ),
        ),
    ]
