# Generated by Django 5.2.16 on 2026-08-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0194_alter_domain_is_enrolled_in_dns_hosting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnsrecord",
            name="tags",
        ),
    ]
