# Generated by Django 5.2.17 on 2026-08-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0194_alter_domain_is_enrolled_in_dns_hosting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dnsrecord",
            options={"verbose_name": "DNS Record", "verbose_name_plural": "DNS Records"},
        ),
    ]
