# Generated by Django 5.2.17 on 2026-08-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0194_alter_domain_is_enrolled_in_dns_hosting"),
        ("registrar", "0195_create_groups_v24"),
    ]

    operations = []
