# Generated by Django 5.2.17 on 2026-08-28 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0195_remove_dnsrecord_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dnsrecord",
            options={"verbose_name": "DNS Record", "verbose_name_plural": "DNS Records"},
        ),
    ]
