# Generated by Django 5.2.16 on 2026-08-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0196_alter_dnsrecord_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="created_at_reference",
        ),
    ]
