# Generated by Django 5.2.17 on 2026-09-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0196_alter_dnsrecord_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="created_at_reference",
        ),
    ]
