"""This file contains general purpose helpers that don't belong in any specific location"""


def get_region(state):
    regions = {
        "CT": 1,
        "ME": 1,
        "MA": 1,
        "NH": 1,
        "RI": 1,
        "VT": 1,
        "NJ": 2,
        "NY": 2,
        "PR": 2,
        "VI": 2,
        "DE": 3,
        "DC": 3,
        "MD": 3,
        "PA": 3,
        "VA": 3,
        "WV": 3,
        "AL": 4,
        "FL": 4,
        "GA": 4,
        "KY": 4,
        "MS": 4,
        "NC": 4,
        "SC": 4,
        "TN": 4,
        "IL": 5,
        "IN": 5,
        "MI": 5,
        "MN": 5,
        "OH": 5,
        "WI": 5,
        "AR": 6,
        "LA": 6,
        "NM": 6,
        "OK": 6,
        "TX": 6,
        "IA": 7,
        "KS": 7,
        "MO": 7,
        "NE": 7,
        "CO": 8,
        "MT": 8,
        "ND": 8,
        "SD": 8,
        "UT": 8,
        "WY": 8,
        "AZ": 9,
        "CA": 9,
        "HI": 9,
        "NV": 9,
        "GU": 9,
        "AS": 9,
        "MP": 9,
        "AK": 10,
        "ID": 10,
        "OR": 10,
        "WA": 10,
    }
    return regions.get(state.upper(), None)
