name: Bug
description: Report a bug or problem with the application
labels: ["bug"]

body:
  - type: markdown
    id: help
    attributes:
      value: |
        > **Note**
        > GitHub Issues use [GitHub Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for formatting.
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: "Please add a concise description of the issue"
      placeholder: "Example: The application shows an internal server error when attempting to apply for a new domain"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "Please add a concise description of the behavior you would expect if this issue were not occurring"
      placeholder: "Example: When submitting a new domain request, the request should be successful, OR if there is a problem with the user's application preventing submission, errors should be enumerated to the user"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        How can the issue be reliably reproduced? Feel free to include screenshots or other supporting artifacts
        
        Example:
        1. In the test environment, fill out the domain request for a new domain
        2. Click the button to trigger a save/submit on the final page and complete the domain request 
        3. See the error
      value: |
        1.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Where is this issue occurring? If related to development environment, list the relevant tool versions.
        
        Example:
        - Environment: Sandbox
        - Browser: Chrome x.y.z
        - Python: x.y.z
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Please include additional references (screenshots, design links, documentation, etc.) that are relevant"
  - type: textarea
    id: issue-links
    attributes:
      label: Issue Links
      description: |
        What other issues does this story relate to and how?
        
        Example:
        - 🚧 Blocked by: #123
        - 🔄 Relates to: #234
