name: Design-Dev Handoff
description: For prepping designs for handoff to developers
labels: ["design"]

body:
  - type: markdown
    id: title-help
    attributes:
      value: |
        > Use handoff in the title and reference the designs being prepped for handoff
  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
      description: |
        Describe what work is being handed off and any other relevant information
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: |
        - [ ] Read the [Design<>Dev Handoff Guide](https://docs.google.com/document/d/1ANpobtbaP9kd924ocWB5tOqFh4YssZtTwkTtLGF2XGY/edit?usp=sharing)
        - [ ] Prep the Figma designs and make sure any content needed is documented in Google Docs as suggested changes
        - [ ] Create or a new issue or edit the existing implementation issue

  - type: textarea
    id: links-to-other-issues
    attributes:
      label: Links to other issues
      description: |
        Use a dash (`-`) to start the line. Add an issue by typing "`#`" then the issue number. Add information to describe any dependancies, blockers, etc. (e.g., 🚧 [construction] Blocks, ⛔️ [no_entry] Is blocked by, 🔄 [arrows_counterclockwise] Relates to). If this is a parent issue, use sub-issues instead of linking other issues here.
      placeholder: "- 🔄 Relates to..."

        
