name: Design Issue / story
description: Specifically for design and content tickets
labels: design, content

body:
  - type: markdown
    id: title-help
    attributes:
      value: |
        > Titles should be short, descriptive, and compelling. Use sentence case: don't capitalize words unnecessarily.
  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
      description: |
        Describe the issue so that someone who wasn't present for its discovery can understand why it matters. For stories, use the user story format (e.g., As a user, I want, so that). Use full sentences, plain language, and [good formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).
    validations:
      required: true
  - type: markdown
    id: acceptance-criteria-design
    attributes:
      value: |
        ### Acceptance criteria for design updates
        - [ ] Used components from the Figma design system wherein possible
        - [ ] Merged draft design(s) into the official registrar or get.gov Figma pages
        - [ ] (If applicable) Updated components from the Figma design system if there's any inconsistencies with production  
        <br>
  - type: markdown
    id: acceptance-criteria-content
    attributes:
      value: |
        ### Acceptance criteria for content updates
        - [ ] Followed the [content guide](https://docs.google.com/document/d/1U-TRx3ecCFZ-qtrCk7EYmF_nmfKh6kd7FV95Pa4iWeM/edit?usp=sharing) instructions, including:
           - [ ] Use official terms in the [word list](https://docs.google.com/document/d/1U-TRx3ecCFZ-qtrCk7EYmF_nmfKh6kd7FV95Pa4iWeM/edit?tab=t.0#heading=h.2et92p0) wherein possible, and avoiding synonyms or alternative terms
           - [ ] Use [content blocks](https://docs.google.com/document/d/1U-TRx3ecCFZ-qtrCk7EYmF_nmfKh6kd7FV95Pa4iWeM/edit?tab=t.0#heading=h.23ckvvd) whenever possible (consider creating new content blocks for new content that will be referenced heavily)
           - [ ] Check for readibility using the [Hemingway Editor](https://hemingwayapp.com/)
           - [ ] Any external links have an [external link icon](https://docs.google.com/document/d/1U-TRx3ecCFZ-qtrCk7EYmF_nmfKh6kd7FV95Pa4iWeM/edit?tab=t.0#heading=h.4i7ojhp) and open in a new tab
        - [ ] Instructions specific to get.gov ([instructions for how to update the public site](https://docs.google.com/document/d/1U-TRx3ecCFZ-qtrCk7EYmF_nmfKh6kd7FV95Pa4iWeM/edit?tab=t.0#heading=h.1pxezwc))
           - [ ] Update content in the get.gov design file in Figma
           - [ ] 
          
          
        <br>
  - type: textarea
    id: additional-acceptance-criteria
    attributes:
      label: Additional acceptance criteria
      description: "If known, add more statements that would need to be true for this issue to be considered resolved. Use a [task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists) if appropriate."
      placeholder: "- [ ]"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Share any other thoughts, like how this might be implemented or fixed. Screenshots and links to documents/discussions are welcome."
  - type: textarea
    id: links-to-other-issues
    attributes:
      label: Links to other issues
      description: |
        "Use a dash (`-`) to start the line. Add an issue by typing "`#`" then the issue number. Add information to describe any dependancies, blockers, etc. (e.g., ðŸš§ [construction] Blocks, â›”ï¸ [no_entry] Is blocked by, ðŸ”„ [arrows_counterclockwise] Relates to). If this is a parent issue, use sub-issues instead of linking other issues here."
      placeholder: "- ðŸ”„ Relates to..."
  - type: markdown
    id: note
    attributes:
      value: |
        > We may edit the text in this issue to document our understanding and clarify the product work.
        

