name: Story
description: Capture actionable sprint work
labels: ["story"]

body:
  - type: markdown
    id: help
    attributes:
      value: |
        > **Note**
        > GitHub Issues use [GitHub Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for formatting.
  - type: textarea
    id: story
    attributes:
      label: Story
      description: |
        Please add the "as a, I want, so that" details that describe the story.
        If more than one "as a, I want, so that" describes the story, add multiple. 
        
        Example:
        As an analyst
        I want the ability to approve a domain request
        so that a request can be fulfilled and a new .gov domain can be provisioned
      value: |
        As a 
        I want
        so that
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Please add the acceptance criteria that best describe the desired outcomes when this work is completed 
        
        Example:
        - Application sends an email when analysts approve domain requests
        - Domain request status is "approved"
        
        Example ("given, when, then" format):
        Given that I am an analyst who has finished reviewing a domain request
        When I click to approve a domain request
        Then the domain provisioning process should be initiated, and the applicant should receive an email update.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Please include additional references (screenshots, design links, documentation, etc.) that are relevant"
  - type: textarea
    id: issue-links
    attributes:
      label: Issue Links
      description: |
        What other issues does this story relate to and how?
        
        Example:
        - 🚧 Blocked by: #123
        - 🔄 Relates to: #234
